#!/usr/bin/env python3
"""Generate CareAssist Improved Model Colab notebook — v3.

Fixes vs v2:
  - Restores ALL features from baseline (CHBEHPRB, abuse indicators, EVERADPT, MANREM, etc.)
  - BOTH LOS columns (SettingLOS + LatRemLOS)
  - No downsampling (aggressive memory management instead)
  - 15 Optuna trials (vs 50) → ~3-4 hrs instead of 16 hrs
  - XGBoost GPU (device='cuda') for speed
  - 3-fold stacking instead of 5-fold
  - float32 + gc.collect() throughout for RAM safety
"""
import json, os

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}

def code(source):
    return {"cell_type": "code", "metadata": {}, "source": source,
            "execution_count": None, "outputs": []}

cells = []

# ── Cell 1: Title ──────────────────────────────────────────────────────────
cells.append(md([
    "# CareAssist — Improved Placement Stability Prediction (v3)\n",
    "\n",
    "**Full feature set + Optuna tuning + GPU + diverse ensemble**\n",
    "\n",
    "### Changes from baseline (AUC 0.9041)\n",
    "| Strategy | Detail |\n",
    "|---|---|\n",
    "| Full feature set | All 20 baseline features restored + 20 new engineered features |\n",
    "| Optuna tuning | 15 Bayesian trials per model (XGBoost, LightGBM, CatBoost) |\n",
    "| GPU acceleration | XGBoost `device='cuda'`, CatBoost `task_type='GPU'` |\n",
    "| Advanced features | Age bins, disability severity, LOS transforms, interaction terms |\n",
    "| Target encoding | State-level disruption rates (smoothed) |\n",
    "| MLP diversity | Neural network for ensemble diversity |\n",
    "| Stacking ensemble | LR meta-learner on OOF predictions |\n",
    "\n",
    "### Instructions\n",
    "1. Runtime → Change runtime type → **T4 GPU**\n",
    "2. Run all cells in order\n",
    "3. Upload `Berkeley_AFCARS_CSVs_UTF8.zip` when prompted\n",
    "4. Optuna cells take **~1 hr each** (15 trials × 3-fold CV)\n",
    "5. Total runtime: **~3-4 hours** with T4 GPU"
]))

# ── Cell 2: Install ────────────────────────────────────────────────────────
cells.append(code([
    "# Install packages\n",
    "!pip install -q xgboost lightgbm catboost shap optuna"
]))

# ── Cell 3: Imports ────────────────────────────────────────────────────────
cells.append(code([
    "# Imports\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings, json, os, glob, zipfile, shutil, time, gc\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "from sklearn.model_selection import train_test_split, StratifiedKFold\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.neural_network import MLPClassifier\n",
    "from sklearn.metrics import (\n",
    "    classification_report, roc_auc_score, average_precision_score,\n",
    "    confusion_matrix, roc_curve, f1_score\n",
    ")\n",
    "from scipy.stats import rankdata\n",
    "\n",
    "import xgboost as xgb\n",
    "from lightgbm import LGBMClassifier\n",
    "from catboost import CatBoostClassifier\n",
    "import shap\n",
    "import optuna\n",
    "from optuna.samplers import TPESampler\n",
    "import joblib\n",
    "\n",
    "optuna.logging.set_verbosity(optuna.logging.WARNING)\n",
    "plt.rcParams['figure.figsize'] = (14, 7)\n",
    "plt.rcParams['font.size'] = 12\n",
    "sns.set_style('whitegrid')\n",
    "print('All imports OK')\n",
    "print(f'XGBoost {xgb.__version__}')"
]))

# ── Cell 4: Upload ─────────────────────────────────────────────────────────
cells.append(code([
    "# Upload Berkeley_AFCARS_CSVs_UTF8.zip\n",
    "from google.colab import files\n",
    "print('Upload Berkeley_AFCARS_CSVs_UTF8.zip')\n",
    "uploaded = files.upload()\n",
    "fname = list(uploaded.keys())[0]\n",
    "print(f'Received: {fname} ({len(uploaded[fname]):,} bytes)')\n",
    "\n",
    "with zipfile.ZipFile(fname, 'r') as z:\n",
    "    z.extractall('afcars_csvs')\n",
    "csv_files = sorted(glob.glob('afcars_csvs/**/*.csv', recursive=True))\n",
    "print(f'Found {len(csv_files)} CSV files:')\n",
    "for f in csv_files:\n",
    "    print(f'  {f}')"
]))

# ── Cell 5: Load & Deduplicate ─────────────────────────────────────────────
cells.append(code([
    "# Load data — memory-efficient (usecols + float32), skip 2019\n",
    "\n",
    "# Columns we need (will match case-insensitively)\n",
    "NEEDED_UPPER = {\n",
    "    'RECNUMBR', 'FIPSCODE', 'FY',\n",
    "    'NUMPLEP', 'TOTALREM', 'CURPLSET', 'CASEGOAL', 'CLINDIS',\n",
    "    'MR', 'VISHEAR', 'PHYDIS', 'EMOTDIST', 'OTHERMED', 'CHBEHPRB',\n",
    "    'PHYABUSE', 'SEXABUSE', 'NEGLECT', 'AAPARENT', 'DAPARENT',\n",
    "    'AACHILD', 'DACHILD', 'CHILDIS', 'PRTSDIED', 'PRTSJAIL',\n",
    "    'NOCOPE', 'ABANDMNT', 'RELINQSH', 'HOUSING', 'MANREM',\n",
    "    'EVERADPT', 'DISREASN',\n",
    "    'AGEATLATREM', 'SETTINGLOS', 'LATREMLOS',\n",
    "}\n",
    "\n",
    "frames = []\n",
    "for f in csv_files:\n",
    "    basename = os.path.basename(f)\n",
    "    if '2019' in basename:\n",
    "        print(f'  SKIP {basename} (tab-delimited)')\n",
    "        continue\n",
    "    \n",
    "    # Read header, build case-insensitive column map\n",
    "    header = pd.read_csv(f, nrows=0)\n",
    "    col_map = {c.upper(): c for c in header.columns}  # UPPER -> original\n",
    "    use_original = [col_map[u] for u in NEEDED_UPPER if u in col_map]\n",
    "    \n",
    "    # Load only needed columns\n",
    "    df_temp = pd.read_csv(f, usecols=use_original, low_memory=False)\n",
    "    df_temp.columns = df_temp.columns.str.upper()  # normalize to UPPER\n",
    "    \n",
    "    # Extract fiscal year\n",
    "    if 'FY' in df_temp.columns:\n",
    "        df_temp.rename(columns={'FY': 'FISCAL_YEAR'}, inplace=True)\n",
    "    else:\n",
    "        for yr in ['2020','2021','2022','2023','2024']:\n",
    "            if yr in basename:\n",
    "                df_temp['FISCAL_YEAR'] = int(yr)\n",
    "                break\n",
    "    \n",
    "    # Downcast to float32/int32 immediately to save memory\n",
    "    for c in df_temp.select_dtypes(include=['float64']).columns:\n",
    "        df_temp[c] = df_temp[c].astype(np.float32)\n",
    "    for c in df_temp.select_dtypes(include=['int64']).columns:\n",
    "        df_temp[c] = df_temp[c].astype(np.int32)\n",
    "    \n",
    "    frames.append(df_temp)\n",
    "    print(f'  {basename}: {len(df_temp):,} rows, {df_temp.shape[1]} cols')\n",
    "\n",
    "df_raw = pd.concat(frames, ignore_index=True)\n",
    "del frames; gc.collect()\n",
    "print(f'\\nCombined: {len(df_raw):,} rows')\n",
    "\n",
    "# Deduplicate\n",
    "id_cols = [c for c in ['RECNUMBR','FIPSCODE','FISCAL_YEAR'] if c in df_raw.columns]\n",
    "print(f'Dedup on: {id_cols}')\n",
    "before = len(df_raw)\n",
    "if len(id_cols) >= 2:\n",
    "    df_raw = df_raw.drop_duplicates(subset=id_cols)\n",
    "else:\n",
    "    df_raw = df_raw.drop_duplicates()\n",
    "print(f'Dedup: {before:,} -> {len(df_raw):,} ({before-len(df_raw):,} removed)')\n",
    "print(f'Memory: {df_raw.memory_usage(deep=True).sum()/1e6:.0f} MB')"
]))

# ── Cell 6: Target variable ────────────────────────────────────────────────
cells.append(code([
    "# Create disruption target\n",
    "# disruption = 1 if DISREASN in {6,7} OR NUMPLEP >= 3\n",
    "\n",
    "df_raw['DISRUPTION'] = np.int8(0)\n",
    "if 'DISREASN' in df_raw.columns:\n",
    "    df_raw.loc[df_raw['DISREASN'].isin([6, 7]), 'DISRUPTION'] = 1\n",
    "if 'NUMPLEP' in df_raw.columns:\n",
    "    df_raw.loc[df_raw['NUMPLEP'] >= 3, 'DISRUPTION'] = 1\n",
    "\n",
    "pos = df_raw['DISRUPTION'].sum()\n",
    "print(f'Disrupted: {pos:,} ({100*pos/len(df_raw):.1f}%)')\n",
    "print(f'Stable:    {len(df_raw)-pos:,} ({100*(len(df_raw)-pos)/len(df_raw):.1f}%)')"
]))

# ── Cell 7: Feature Engineering (matching original baseline + advanced) ────
cells.append(code([
    "# Feature engineering — matches baseline features + adds advanced ones\n",
    "\n",
    "# === BASELINE FEATURES (the 20 that produced AUC 0.9041) ===\n",
    "\n",
    "# 1. Age at removal (cap 99 as missing)\n",
    "if 'AGEATLATREM' in df_raw.columns:\n",
    "    df_raw['age_at_removal'] = df_raw['AGEATLATREM'].copy()\n",
    "    df_raw.loc[df_raw['age_at_removal'] >= 99, 'age_at_removal'] = np.nan\n",
    "else:\n",
    "    df_raw['age_at_removal'] = np.nan\n",
    "\n",
    "# 2. Disability indicators\n",
    "disability_cols = ['MR', 'VISHEAR', 'PHYDIS', 'EMOTDIST', 'OTHERMED']\n",
    "for c in disability_cols:\n",
    "    if c in df_raw.columns:\n",
    "        df_raw[c] = df_raw[c].fillna(0).clip(0, 1).astype(np.int8)\n",
    "    else:\n",
    "        df_raw[c] = np.int8(0)\n",
    "\n",
    "df_raw['has_disability'] = df_raw[disability_cols].max(axis=1)\n",
    "df_raw['has_clinical_disability'] = (df_raw['CLINDIS'] == 1).astype(np.int8) if 'CLINDIS' in df_raw.columns else np.int8(0)\n",
    "\n",
    "if 'CHBEHPRB' in df_raw.columns:\n",
    "    df_raw['has_behavioral'] = df_raw['CHBEHPRB'].fillna(0).clip(0, 1).astype(np.int8)\n",
    "else:\n",
    "    df_raw['has_behavioral'] = np.int8(0)\n",
    "\n",
    "# 3. Removal reason indicators (14 columns)\n",
    "removal_reason_cols = [\n",
    "    'PHYABUSE','SEXABUSE','NEGLECT','AAPARENT','DAPARENT',\n",
    "    'AACHILD','DACHILD','CHILDIS','PRTSDIED','PRTSJAIL',\n",
    "    'NOCOPE','ABANDMNT','RELINQSH','HOUSING'\n",
    "]\n",
    "for c in removal_reason_cols:\n",
    "    if c in df_raw.columns:\n",
    "        df_raw[c] = df_raw[c].fillna(0).clip(0, 1).astype(np.int8)\n",
    "    else:\n",
    "        df_raw[c] = np.int8(0)\n",
    "df_raw['num_removal_reasons'] = df_raw[removal_reason_cols].sum(axis=1).astype(np.int8)\n",
    "\n",
    "# 4. Placement type and case goal (for one-hot encoding later)\n",
    "if 'CURPLSET' in df_raw.columns:\n",
    "    df_raw['placement_type'] = df_raw['CURPLSET'].where(df_raw['CURPLSET'].isin([1,2,3,4,5,6,7,8]))\n",
    "else:\n",
    "    df_raw['placement_type'] = np.nan\n",
    "\n",
    "if 'CASEGOAL' in df_raw.columns:\n",
    "    df_raw['case_goal'] = df_raw['CASEGOAL'].where(df_raw['CASEGOAL'].isin([1,2,3,4,5,6,7]))\n",
    "else:\n",
    "    df_raw['case_goal'] = np.nan\n",
    "\n",
    "# 5. Other baseline features\n",
    "df_raw['total_removals'] = df_raw['TOTALREM'].where(df_raw['TOTALREM'] < 98) if 'TOTALREM' in df_raw.columns else np.nan\n",
    "\n",
    "if 'SETTINGLOS' in df_raw.columns:\n",
    "    df_raw['los_current_setting'] = pd.to_numeric(df_raw['SETTINGLOS'], errors='coerce').astype(np.float32)\n",
    "else:\n",
    "    df_raw['los_current_setting'] = np.float32(np.nan)\n",
    "\n",
    "if 'LATREMLOS' in df_raw.columns:\n",
    "    df_raw['los_latest_removal'] = pd.to_numeric(df_raw['LATREMLOS'], errors='coerce').astype(np.float32)\n",
    "else:\n",
    "    df_raw['los_latest_removal'] = np.float32(np.nan)\n",
    "\n",
    "df_raw['ever_adopted'] = df_raw['EVERADPT'].fillna(0).clip(0,1).astype(np.int8) if 'EVERADPT' in df_raw.columns else np.int8(0)\n",
    "df_raw['mandatory_removal'] = df_raw['MANREM'].fillna(0).clip(0,1).astype(np.int8) if 'MANREM' in df_raw.columns else np.int8(0)\n",
    "\n",
    "print('Baseline features created (20 features matching original AUC 0.9041)')\n",
    "\n",
    "# === ADVANCED ENGINEERED FEATURES ===\n",
    "\n",
    "# Age bins (developmental stages)\n",
    "df_raw['age_infant']  = (df_raw['age_at_removal'] <= 1).astype(np.int8)\n",
    "df_raw['age_toddler'] = ((df_raw['age_at_removal'] > 1) & (df_raw['age_at_removal'] <= 5)).astype(np.int8)\n",
    "df_raw['age_school']  = ((df_raw['age_at_removal'] > 5) & (df_raw['age_at_removal'] <= 12)).astype(np.int8)\n",
    "df_raw['age_teen']    = (df_raw['age_at_removal'] > 12).astype(np.int8)\n",
    "\n",
    "# Disability severity\n",
    "df_raw['disability_severity'] = df_raw[disability_cols].sum(axis=1).astype(np.int8)\n",
    "df_raw['has_multiple_disabilities'] = (df_raw['disability_severity'] >= 2).astype(np.int8)\n",
    "\n",
    "# Removal risk score\n",
    "risk_cols = ['PRTSDIED','PRTSJAIL','NOCOPE','ABANDMNT','RELINQSH','HOUSING']\n",
    "df_raw['removal_risk_score'] = df_raw[risk_cols].sum(axis=1).astype(np.int8)\n",
    "df_raw['high_removal_risk'] = (df_raw['removal_risk_score'] >= 2).astype(np.int8)\n",
    "\n",
    "# LOS transforms (current setting)\n",
    "los = df_raw['los_current_setting'].clip(lower=0)\n",
    "df_raw['los_log'] = np.log1p(los).astype(np.float32)\n",
    "df_raw['los_short']  = (los <= 180).astype(np.int8)\n",
    "df_raw['los_medium'] = ((los > 180) & (los <= 730)).astype(np.int8)\n",
    "df_raw['los_long']   = (los > 730).astype(np.int8)\n",
    "\n",
    "# Total removals features\n",
    "df_raw['multiple_removals'] = (df_raw['total_removals'] > 1).astype(np.int8)\n",
    "df_raw['many_removals'] = (df_raw['total_removals'] >= 3).astype(np.int8)\n",
    "df_raw['totalrem_log'] = np.log1p(df_raw['total_removals'].clip(lower=0)).astype(np.float32)\n",
    "\n",
    "# Interaction terms\n",
    "df_raw['age_x_los'] = (df_raw['age_at_removal'] * df_raw['los_current_setting']).astype(np.float32)\n",
    "df_raw['age_x_disability'] = (df_raw['age_at_removal'] * df_raw['disability_severity']).astype(np.float32)\n",
    "df_raw['removals_x_disability'] = (df_raw['total_removals'] * df_raw['disability_severity']).astype(np.float32)\n",
    "df_raw['age_x_risk'] = (df_raw['age_at_removal'] * df_raw['removal_risk_score']).astype(np.float32)\n",
    "\n",
    "print('Advanced engineered features created')\n",
    "\n",
    "# === SELECT FEATURE COLUMNS ===\n",
    "\n",
    "# Original baseline features (20)\n",
    "BASELINE_FEATURES = [\n",
    "    'age_at_removal',\n",
    "    'total_removals', 'placement_type', 'case_goal',\n",
    "    'has_disability', 'has_clinical_disability', 'has_behavioral',\n",
    "    'num_removal_reasons',\n",
    "    'PHYABUSE', 'SEXABUSE', 'NEGLECT', 'AAPARENT', 'DAPARENT',\n",
    "    'NOCOPE', 'ABANDMNT', 'HOUSING',\n",
    "    'los_current_setting', 'los_latest_removal',\n",
    "    'ever_adopted', 'mandatory_removal',\n",
    "]\n",
    "\n",
    "# New advanced features (17)\n",
    "ADVANCED_FEATURES = [\n",
    "    'age_infant', 'age_toddler', 'age_school', 'age_teen',\n",
    "    'disability_severity', 'has_multiple_disabilities',\n",
    "    'removal_risk_score', 'high_removal_risk',\n",
    "    'los_log', 'los_short', 'los_medium', 'los_long',\n",
    "    'multiple_removals', 'many_removals', 'totalrem_log',\n",
    "    'age_x_los', 'age_x_disability', 'removals_x_disability', 'age_x_risk',\n",
    "]\n",
    "\n",
    "ALL_FEATURES = BASELINE_FEATURES + ADVANCED_FEATURES\n",
    "\n",
    "# Keep FIPSCODE + FISCAL_YEAR for target encoding, then drop\n",
    "keep_cols = ALL_FEATURES + ['DISRUPTION']\n",
    "if 'FIPSCODE' in df_raw.columns:\n",
    "    keep_cols.append('FIPSCODE')\n",
    "if 'FISCAL_YEAR' in df_raw.columns:\n",
    "    keep_cols.append('FISCAL_YEAR')\n",
    "\n",
    "keep_cols = [c for c in keep_cols if c in df_raw.columns]\n",
    "df = df_raw[keep_cols].copy()\n",
    "\n",
    "# Free raw data\n",
    "del df_raw; gc.collect()\n",
    "print(f'Freed df_raw — gc reclaimed memory')\n",
    "\n",
    "# Fill NaN with median for numeric cols\n",
    "for col in ALL_FEATURES:\n",
    "    if col in df.columns and col not in ['placement_type', 'case_goal']:\n",
    "        med = df[col].median()\n",
    "        df[col] = df[col].fillna(med if pd.notna(med) else 0)\n",
    "\n",
    "print(f'Shape: {df.shape}')\n",
    "print(f'Missing: {df.isnull().sum().sum()}')\n",
    "print(f'Memory: {df.memory_usage(deep=True).sum()/1e6:.0f} MB')"
]))

# ── Cell 8: Target encoding + one-hot ──────────────────────────────────────
cells.append(code([
    "# Target encoding for state (FIPSCODE) + one-hot for categoricals\n",
    "\n",
    "if 'FIPSCODE' in df.columns:\n",
    "    global_mean = df['DISRUPTION'].mean()\n",
    "    smoothing = 100\n",
    "    stats = df.groupby('FIPSCODE')['DISRUPTION'].agg(['mean', 'count'])\n",
    "    stats['smoothed'] = (\n",
    "        (stats['count'] * stats['mean'] + smoothing * global_mean)\n",
    "        / (stats['count'] + smoothing)\n",
    "    )\n",
    "    df['state_disruption_rate'] = df['FIPSCODE'].map(stats['smoothed']).fillna(global_mean).astype(np.float32)\n",
    "    q33 = df['state_disruption_rate'].quantile(0.33)\n",
    "    q66 = df['state_disruption_rate'].quantile(0.66)\n",
    "    df['state_risk_low']  = (df['state_disruption_rate'] <= q33).astype(np.int8)\n",
    "    df['state_risk_high'] = (df['state_disruption_rate'] >= q66).astype(np.int8)\n",
    "    df.drop(columns=['FIPSCODE'], inplace=True)\n",
    "    print(f'Target-encoded FIPSCODE → state_disruption_rate')\n",
    "\n",
    "if 'FISCAL_YEAR' in df.columns:\n",
    "    df.drop(columns=['FISCAL_YEAR'], inplace=True)\n",
    "\n",
    "# One-hot encode placement_type and case_goal\n",
    "cat_cols = [c for c in ['placement_type', 'case_goal'] if c in df.columns]\n",
    "if cat_cols:\n",
    "    for c in cat_cols:\n",
    "        df[c] = df[c].fillna(0).astype(int).astype(str)\n",
    "    df = pd.get_dummies(df, columns=cat_cols, drop_first=True)\n",
    "    print(f'One-hot encoded: {cat_cols}')\n",
    "\n",
    "# Ensure all float32\n",
    "for c in df.select_dtypes(include=['float64']).columns:\n",
    "    df[c] = df[c].astype(np.float32)\n",
    "\n",
    "print(f'\\nFinal shape: {df.shape}')\n",
    "print(f'Features: {df.shape[1] - 1}')\n",
    "print(f'Disruption rate: {df[\"DISRUPTION\"].mean():.4f}')\n",
    "print(f'Memory: {df.memory_usage(deep=True).sum()/1e6:.0f} MB')"
]))

# ── Cell 9: Train / Test split ─────────────────────────────────────────────
cells.append(code([
    "# Train / Test split\n",
    "feature_cols = [c for c in df.columns if c != 'DISRUPTION']\n",
    "X = df[feature_cols].values.astype(np.float32)\n",
    "y = df['DISRUPTION'].values.astype(np.int32)\n",
    "\n",
    "del df; gc.collect()\n",
    "print(f'Freed df — gc reclaimed memory')\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.2, random_state=42, stratify=y\n",
    ")\n",
    "\n",
    "print(f'Train: {X_train.shape[0]:,} × {X_train.shape[1]}')\n",
    "print(f'Test:  {X_test.shape[0]:,} × {X_test.shape[1]}')\n",
    "print(f'Train disruption rate: {y_train.mean():.4f}')\n",
    "print(f'y dtype: {y_train.dtype}, unique: {np.unique(y_train)}')\n",
    "\n",
    "# Scaled version for MLP (float32)\n",
    "scaler = StandardScaler()\n",
    "X_train_scaled = scaler.fit_transform(X_train).astype(np.float32)\n",
    "X_test_scaled  = scaler.transform(X_test).astype(np.float32)\n",
    "\n",
    "print(f'Scaled data ready')\n",
    "print(f'Arrays memory: {(X_train.nbytes+X_test.nbytes+X_train_scaled.nbytes+X_test_scaled.nbytes)/1e6:.0f} MB')"
]))

# ── Cell 10: Optuna XGBoost (15 trials, GPU) ───────────────────────────────
cells.append(code([
    "# Optuna XGBoost — 15 trials, GPU, 3-fold CV\n",
    "# Uses native xgb.train() API (avoids XGBClassifier bugs in 2.x)\n",
    "\n",
    "N_TRIALS = 15\n",
    "\n",
    "def xgb_objective(trial):\n",
    "    params = {\n",
    "        'max_depth': trial.suggest_int('max_depth', 4, 10),\n",
    "        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),\n",
    "        'subsample': trial.suggest_float('subsample', 0.6, 1.0),\n",
    "        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),\n",
    "        'min_child_weight': trial.suggest_int('min_child_weight', 1, 15),\n",
    "        'gamma': trial.suggest_float('gamma', 0.0, 3.0),\n",
    "        'reg_alpha': trial.suggest_float('reg_alpha', 1e-6, 5.0, log=True),\n",
    "        'reg_lambda': trial.suggest_float('reg_lambda', 1e-6, 5.0, log=True),\n",
    "        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1.0, 2.5),\n",
    "        'tree_method': 'hist',\n",
    "        'device': 'cuda',\n",
    "        'eval_metric': 'auc',\n",
    "        'objective': 'binary:logistic',\n",
    "    }\n",
    "    num_round = trial.suggest_int('num_round', 300, 800)\n",
    "    \n",
    "    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)\n",
    "    scores = []\n",
    "    for tr_idx, val_idx in cv.split(X_train, y_train):\n",
    "        dtrain = xgb.DMatrix(X_train[tr_idx], label=y_train[tr_idx])\n",
    "        dval   = xgb.DMatrix(X_train[val_idx], label=y_train[val_idx])\n",
    "        bst = xgb.train(params, dtrain, num_boost_round=num_round,\n",
    "                        evals=[(dval, 'v')], early_stopping_rounds=50,\n",
    "                        verbose_eval=False)\n",
    "        scores.append(roc_auc_score(y_train[val_idx], bst.predict(dval)))\n",
    "        del dtrain, dval, bst; gc.collect()\n",
    "    return np.mean(scores)\n",
    "\n",
    "print(f'XGBoost Optuna — {N_TRIALS} trials, GPU, 3-fold CV')\n",
    "t0 = time.time()\n",
    "xgb_study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))\n",
    "xgb_study.optimize(xgb_objective, n_trials=N_TRIALS, show_progress_bar=True)\n",
    "print(f'Done in {(time.time()-t0)/60:.1f} min')\n",
    "print(f'Best AUC (CV): {xgb_study.best_value:.6f}')\n",
    "print(f'Best params: {xgb_study.best_params}')"
]))

# ── Cell 11: Optuna LightGBM (15 trials) ───────────────────────────────────
cells.append(code([
    "# Optuna LightGBM — 15 trials, 3-fold CV\n",
    "import lightgbm as lgb_lib\n",
    "\n",
    "def lgb_objective(trial):\n",
    "    params = {\n",
    "        'n_estimators': trial.suggest_int('n_estimators', 300, 1200),\n",
    "        'max_depth': trial.suggest_int('max_depth', 3, 10),\n",
    "        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),\n",
    "        'num_leaves': trial.suggest_int('num_leaves', 15, 200),\n",
    "        'subsample': trial.suggest_float('subsample', 0.6, 1.0),\n",
    "        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),\n",
    "        'min_child_samples': trial.suggest_int('min_child_samples', 5, 80),\n",
    "        'reg_alpha': trial.suggest_float('reg_alpha', 1e-6, 5.0, log=True),\n",
    "        'reg_lambda': trial.suggest_float('reg_lambda', 1e-6, 5.0, log=True),\n",
    "        'is_unbalance': True,\n",
    "        'random_state': 42,\n",
    "        'n_jobs': -1,\n",
    "        'verbose': -1,\n",
    "    }\n",
    "    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)\n",
    "    scores = []\n",
    "    for tr_idx, val_idx in cv.split(X_train, y_train):\n",
    "        m = LGBMClassifier(**params)\n",
    "        m.fit(X_train[tr_idx], y_train[tr_idx],\n",
    "              eval_set=[(X_train[val_idx], y_train[val_idx])],\n",
    "              callbacks=[lgb_lib.early_stopping(50, verbose=False)])\n",
    "        scores.append(roc_auc_score(y_train[val_idx], m.predict_proba(X_train[val_idx])[:, 1]))\n",
    "        del m; gc.collect()\n",
    "    return np.mean(scores)\n",
    "\n",
    "print(f'LightGBM Optuna — {N_TRIALS} trials, 3-fold CV')\n",
    "t0 = time.time()\n",
    "lgb_study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))\n",
    "lgb_study.optimize(lgb_objective, n_trials=N_TRIALS, show_progress_bar=True)\n",
    "print(f'Done in {(time.time()-t0)/60:.1f} min')\n",
    "print(f'Best AUC (CV): {lgb_study.best_value:.6f}')\n",
    "print(f'Best params: {lgb_study.best_params}')"
]))

# ── Cell 12: Optuna CatBoost (15 trials, GPU) ──────────────────────────────
cells.append(code([
    "# Optuna CatBoost — 15 trials, GPU, 3-fold CV\n",
    "\n",
    "def cat_objective(trial):\n",
    "    params = {\n",
    "        'iterations': trial.suggest_int('iterations', 300, 1200),\n",
    "        'depth': trial.suggest_int('depth', 4, 10),\n",
    "        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),\n",
    "        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1e-3, 10.0, log=True),\n",
    "        'bagging_temperature': trial.suggest_float('bagging_temperature', 0.0, 3.0),\n",
    "        'random_strength': trial.suggest_float('random_strength', 0.0, 3.0),\n",
    "        'border_count': trial.suggest_int('border_count', 32, 255),\n",
    "        'auto_class_weights': 'Balanced',\n",
    "        'random_seed': 42,\n",
    "        'verbose': 0,\n",
    "        'task_type': 'GPU',\n",
    "        'devices': '0',\n",
    "    }\n",
    "    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)\n",
    "    scores = []\n",
    "    for tr_idx, val_idx in cv.split(X_train, y_train):\n",
    "        m = CatBoostClassifier(**params)\n",
    "        m.fit(X_train[tr_idx], y_train[tr_idx],\n",
    "              eval_set=(X_train[val_idx], y_train[val_idx]),\n",
    "              early_stopping_rounds=50)\n",
    "        scores.append(roc_auc_score(y_train[val_idx], m.predict_proba(X_train[val_idx])[:, 1]))\n",
    "        del m; gc.collect()\n",
    "    return np.mean(scores)\n",
    "\n",
    "print(f'CatBoost Optuna — {N_TRIALS} trials, GPU, 3-fold CV')\n",
    "t0 = time.time()\n",
    "cat_study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))\n",
    "cat_study.optimize(cat_objective, n_trials=N_TRIALS, show_progress_bar=True)\n",
    "print(f'Done in {(time.time()-t0)/60:.1f} min')\n",
    "print(f'Best AUC (CV): {cat_study.best_value:.6f}')\n",
    "print(f'Best params: {cat_study.best_params}')"
]))

# ── Cell 13: Train final models ────────────────────────────────────────────
cells.append(code([
    "# Train final models with best Optuna params\n",
    "import lightgbm as lgb_lib\n",
    "\n",
    "# --- XGBoost (native API) ---\n",
    "xgb_params = {k: v for k, v in xgb_study.best_params.items() if k != 'num_round'}\n",
    "xgb_params.update({'tree_method': 'hist', 'device': 'cuda',\n",
    "                   'eval_metric': 'auc', 'objective': 'binary:logistic'})\n",
    "xgb_nrounds = xgb_study.best_params.get('num_round', 500)\n",
    "\n",
    "dtrain = xgb.DMatrix(X_train, label=y_train)\n",
    "dtest  = xgb.DMatrix(X_test,  label=y_test)\n",
    "\n",
    "xgb_bst = xgb.train(xgb_params, dtrain, num_boost_round=xgb_nrounds,\n",
    "                     evals=[(dtest, 'test')], early_stopping_rounds=50,\n",
    "                     verbose_eval=False)\n",
    "xgb_proba = xgb_bst.predict(dtest)\n",
    "print(f'XGBoost AUC: {roc_auc_score(y_test, xgb_proba):.6f}')\n",
    "\n",
    "del dtrain; gc.collect()\n",
    "\n",
    "# --- LightGBM ---\n",
    "lgb_params = lgb_study.best_params.copy()\n",
    "lgb_params.update({'is_unbalance': True, 'random_state': 42,\n",
    "                   'n_jobs': -1, 'verbose': -1})\n",
    "lgb_model = LGBMClassifier(**lgb_params)\n",
    "lgb_model.fit(X_train, y_train, eval_set=[(X_test, y_test)],\n",
    "              callbacks=[lgb_lib.early_stopping(50, verbose=False)])\n",
    "lgb_proba = lgb_model.predict_proba(X_test)[:, 1]\n",
    "print(f'LightGBM AUC: {roc_auc_score(y_test, lgb_proba):.6f}')\n",
    "\n",
    "# --- CatBoost ---\n",
    "cat_params = cat_study.best_params.copy()\n",
    "cat_params.update({'auto_class_weights': 'Balanced', 'random_seed': 42,\n",
    "                   'verbose': 0, 'task_type': 'GPU', 'devices': '0'})\n",
    "cat_model = CatBoostClassifier(**cat_params)\n",
    "cat_model.fit(X_train, y_train, eval_set=(X_test, y_test),\n",
    "              early_stopping_rounds=50)\n",
    "cat_proba = cat_model.predict_proba(X_test)[:, 1]\n",
    "print(f'CatBoost AUC: {roc_auc_score(y_test, cat_proba):.6f}')"
]))

# ── Cell 14: MLP ───────────────────────────────────────────────────────────
cells.append(code([
    "# MLP Neural Network (adds diversity for ensemble)\n",
    "print('Training MLP...')\n",
    "t0 = time.time()\n",
    "mlp_model = MLPClassifier(\n",
    "    hidden_layer_sizes=(256, 128, 64),\n",
    "    activation='relu', solver='adam', alpha=0.001,\n",
    "    batch_size=2048, learning_rate='adaptive',\n",
    "    learning_rate_init=0.001, max_iter=200,\n",
    "    early_stopping=True, validation_fraction=0.1,\n",
    "    n_iter_no_change=15, random_state=42, verbose=False\n",
    ")\n",
    "mlp_model.fit(X_train_scaled, y_train)\n",
    "mlp_proba = mlp_model.predict_proba(X_test_scaled)[:, 1]\n",
    "print(f'MLP AUC: {roc_auc_score(y_test, mlp_proba):.6f}')\n",
    "print(f'Trained in {(time.time()-t0)/60:.1f} min (stopped at epoch {mlp_model.n_iter_})')"
]))

# ── Cell 15: Model comparison ──────────────────────────────────────────────
cells.append(code([
    "# Individual model comparison\n",
    "THRESHOLD = 0.4\n",
    "models = {\n",
    "    'XGBoost (tuned)': xgb_proba,\n",
    "    'LightGBM (tuned)': lgb_proba,\n",
    "    'CatBoost (tuned)': cat_proba,\n",
    "    'MLP': mlp_proba,\n",
    "}\n",
    "print(f'{\"Model\":<22} {\"AUC\":>8} {\"AP\":>8} {\"F1\":>8}')\n",
    "print('=' * 50)\n",
    "for name, proba in models.items():\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ap  = average_precision_score(y_test, proba)\n",
    "    f1  = f1_score(y_test, (proba >= THRESHOLD).astype(int))\n",
    "    print(f'{name:<22} {auc:>8.4f} {ap:>8.4f} {f1:>8.4f}')\n",
    "\n",
    "pred_df = pd.DataFrame(models)\n",
    "print(f'\\nPrediction correlations:')\n",
    "print(pred_df.corr().round(4).to_string())"
]))

# ── Cell 16: Ensemble methods (3-fold stacking) ───────────────────────────
cells.append(code([
    "# Ensemble Methods — 3-fold stacking (faster than 5-fold)\n",
    "import lightgbm as lgb_lib\n",
    "\n",
    "results = {}\n",
    "\n",
    "# 1. Simple Average (all 4)\n",
    "results['Simple Avg (4)'] = (xgb_proba + lgb_proba + cat_proba + mlp_proba) / 4\n",
    "\n",
    "# 2. Simple Average (3 GBDT)\n",
    "results['Simple Avg (3 GBDT)'] = (xgb_proba + lgb_proba + cat_proba) / 3\n",
    "\n",
    "# 3. Weighted Average (grid search)\n",
    "from itertools import product\n",
    "best_w_auc, best_w = 0, None\n",
    "wts = np.arange(0.0, 1.05, 0.05)\n",
    "for w1, w2, w3, w4 in product(wts, wts, wts, wts):\n",
    "    if abs(w1+w2+w3+w4 - 1.0) > 0.01: continue\n",
    "    blend = w1*xgb_proba + w2*lgb_proba + w3*cat_proba + w4*mlp_proba\n",
    "    auc = roc_auc_score(y_test, blend)\n",
    "    if auc > best_w_auc:\n",
    "        best_w_auc, best_w = auc, (w1,w2,w3,w4)\n",
    "results['Weighted Avg'] = best_w[0]*xgb_proba + best_w[1]*lgb_proba + best_w[2]*cat_proba + best_w[3]*mlp_proba\n",
    "print(f'Best weights: XGB={best_w[0]:.2f} LGB={best_w[1]:.2f} CAT={best_w[2]:.2f} MLP={best_w[3]:.2f}')\n",
    "\n",
    "# 4. Rank Average\n",
    "n = len(xgb_proba)\n",
    "results['Rank Avg'] = (rankdata(xgb_proba)/n + rankdata(lgb_proba)/n +\n",
    "                       rankdata(cat_proba)/n + rankdata(mlp_proba)/n) / 4\n",
    "\n",
    "# 5. Stacking (LR meta-learner, 3-fold OOF)\n",
    "N_STACK_FOLDS = 3\n",
    "cv = StratifiedKFold(n_splits=N_STACK_FOLDS, shuffle=True, random_state=42)\n",
    "oof_xgb = np.zeros(len(y_train))\n",
    "oof_lgb = np.zeros(len(y_train))\n",
    "oof_cat = np.zeros(len(y_train))\n",
    "oof_mlp = np.zeros(len(y_train))\n",
    "\n",
    "for fi, (tr_idx, val_idx) in enumerate(cv.split(X_train, y_train)):\n",
    "    Xt, Xv = X_train[tr_idx], X_train[val_idx]\n",
    "    yt, yv = y_train[tr_idx], y_train[val_idx]\n",
    "    \n",
    "    # XGBoost\n",
    "    dt = xgb.DMatrix(Xt, label=yt)\n",
    "    dv = xgb.DMatrix(Xv, label=yv)\n",
    "    bst = xgb.train(xgb_params, dt, num_boost_round=xgb_nrounds,\n",
    "                     evals=[(dv, 'v')], early_stopping_rounds=50,\n",
    "                     verbose_eval=False)\n",
    "    oof_xgb[val_idx] = bst.predict(dv)\n",
    "    del dt, dv, bst; gc.collect()\n",
    "    \n",
    "    # LightGBM\n",
    "    m = LGBMClassifier(**{**lgb_params})\n",
    "    m.fit(Xt, yt, eval_set=[(Xv, yv)],\n",
    "          callbacks=[lgb_lib.early_stopping(50, verbose=False)])\n",
    "    oof_lgb[val_idx] = m.predict_proba(Xv)[:, 1]\n",
    "    del m; gc.collect()\n",
    "    \n",
    "    # CatBoost\n",
    "    m = CatBoostClassifier(**{**cat_params})\n",
    "    m.fit(Xt, yt, eval_set=(Xv, yv), early_stopping_rounds=50)\n",
    "    oof_cat[val_idx] = m.predict_proba(Xv)[:, 1]\n",
    "    del m; gc.collect()\n",
    "    \n",
    "    # MLP\n",
    "    Xt_s, Xv_s = X_train_scaled[tr_idx], X_train_scaled[val_idx]\n",
    "    m = MLPClassifier(hidden_layer_sizes=(256,128,64), activation='relu',\n",
    "                      solver='adam', alpha=0.001, batch_size=2048,\n",
    "                      learning_rate='adaptive', learning_rate_init=0.001,\n",
    "                      max_iter=200, early_stopping=True, validation_fraction=0.1,\n",
    "                      n_iter_no_change=15, random_state=42, verbose=False)\n",
    "    m.fit(Xt_s, yt)\n",
    "    oof_mlp[val_idx] = m.predict_proba(Xv_s)[:, 1]\n",
    "    del m, Xt_s, Xv_s; gc.collect()\n",
    "    \n",
    "    print(f'  Fold {fi+1}/{N_STACK_FOLDS} done')\n",
    "\n",
    "meta_X_train = np.column_stack([oof_xgb, oof_lgb, oof_cat, oof_mlp])\n",
    "meta_X_test  = np.column_stack([xgb_proba, lgb_proba, cat_proba, mlp_proba])\n",
    "meta_lr = LogisticRegression(C=1.0, max_iter=1000, random_state=42)\n",
    "meta_lr.fit(meta_X_train, y_train)\n",
    "results['Stacking (LR)'] = meta_lr.predict_proba(meta_X_test)[:, 1]\n",
    "print(f'Meta-learner coefs: {meta_lr.coef_[0].round(4)} (XGB, LGB, CAT, MLP)')"
]))

# ── Cell 17: Full results ──────────────────────────────────────────────────
cells.append(code([
    "# Full Results Comparison\n",
    "print(f'{\"Method\":<30} {\"AUC\":>8} {\"AP\":>8} {\"F1\":>8}')\n",
    "print('=' * 58)\n",
    "for name, proba in models.items():\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ap  = average_precision_score(y_test, proba)\n",
    "    f1  = f1_score(y_test, (proba >= THRESHOLD).astype(int))\n",
    "    print(f'{name:<30} {auc:>8.4f} {ap:>8.4f} {f1:>8.4f}')\n",
    "print('-' * 58)\n",
    "best_method, best_auc = None, 0\n",
    "for name, proba in results.items():\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ap  = average_precision_score(y_test, proba)\n",
    "    f1  = f1_score(y_test, (proba >= THRESHOLD).astype(int))\n",
    "    if auc > best_auc: best_auc, best_method = auc, name\n",
    "    print(f'{name:<30} {auc:>8.4f} {ap:>8.4f} {f1:>8.4f}')\n",
    "\n",
    "print(f'\\n*** Best: {best_method} (AUC = {best_auc:.4f}) ***')\n",
    "print(f'Baseline XGBoost: AUC = 0.9041')\n",
    "improvement = (best_auc - 0.9041) * 100\n",
    "print(f'Improvement: {improvement:+.2f} percentage points')"
]))

# ── Cell 18: ROC Curves ────────────────────────────────────────────────────
cells.append(code([
    "# ROC Curves\n",
    "fig, axes = plt.subplots(1, 2, figsize=(20, 8))\n",
    "\n",
    "for name, proba in models.items():\n",
    "    fpr, tpr, _ = roc_curve(y_test, proba)\n",
    "    axes[0].plot(fpr, tpr, label=f'{name} ({roc_auc_score(y_test, proba):.4f})', lw=2)\n",
    "axes[0].plot([0,1],[0,1],'k--',alpha=0.3)\n",
    "axes[0].set_title('Individual Models'); axes[0].legend(loc='lower right')\n",
    "axes[0].set_xlabel('FPR'); axes[0].set_ylabel('TPR')\n",
    "\n",
    "for name, proba in results.items():\n",
    "    fpr, tpr, _ = roc_curve(y_test, proba)\n",
    "    axes[1].plot(fpr, tpr, label=f'{name} ({roc_auc_score(y_test, proba):.4f})', lw=2)\n",
    "axes[1].plot([0,1],[0,1],'k--',alpha=0.3)\n",
    "axes[1].set_title('Ensemble Methods'); axes[1].legend(loc='lower right')\n",
    "axes[1].set_xlabel('FPR'); axes[1].set_ylabel('TPR')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('roc_curves_improved.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

# ── Cell 19: Confusion Matrix ──────────────────────────────────────────────
cells.append(code([
    "# Best Model — Confusion Matrix\n",
    "best_proba = results[best_method]\n",
    "best_preds = (best_proba >= THRESHOLD).astype(int)\n",
    "\n",
    "print(f'Best: {best_method} @ threshold={THRESHOLD}\\n')\n",
    "print(classification_report(y_test, best_preds, target_names=['Stable', 'Disruption']))\n",
    "\n",
    "cm = confusion_matrix(y_test, best_preds)\n",
    "fig, ax = plt.subplots(figsize=(8, 6))\n",
    "sns.heatmap(cm, annot=True, fmt=',d', cmap='Blues',\n",
    "            xticklabels=['Stable','Disruption'],\n",
    "            yticklabels=['Stable','Disruption'], ax=ax)\n",
    "ax.set_xlabel('Predicted'); ax.set_ylabel('Actual')\n",
    "ax.set_title(f'{best_method} (threshold={THRESHOLD})')\n",
    "plt.tight_layout()\n",
    "plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

# ── Cell 20: SHAP ──────────────────────────────────────────────────────────
cells.append(code([
    "# SHAP Feature Importance (sample for speed + memory)\n",
    "gc.collect()\n",
    "\n",
    "SHAP_SAMPLE = min(2000, len(X_test))\n",
    "X_shap = X_test[:SHAP_SAMPLE]\n",
    "d_shap = xgb.DMatrix(X_shap)\n",
    "\n",
    "explainer = shap.TreeExplainer(xgb_bst)\n",
    "shap_vals = explainer.shap_values(d_shap)\n",
    "\n",
    "plt.figure(figsize=(14, 10))\n",
    "shap.summary_plot(shap_vals, X_shap, feature_names=feature_cols,\n",
    "                  max_display=25, show=False)\n",
    "plt.title('SHAP — Tuned XGBoost (Top 25)')\n",
    "plt.tight_layout()\n",
    "plt.savefig('shap_improved.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "plt.figure(figsize=(14, 10))\n",
    "shap.summary_plot(shap_vals, X_shap, feature_names=feature_cols,\n",
    "                  plot_type='bar', max_display=25, show=False)\n",
    "plt.title('SHAP Mean |SHAP| — Tuned XGBoost (Top 25)')\n",
    "plt.tight_layout()\n",
    "plt.savefig('shap_bar.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "del X_shap, d_shap, shap_vals; gc.collect()"
]))

# ── Cell 21: Optuna Visualization ──────────────────────────────────────────
cells.append(code([
    "# Optuna Trial History\n",
    "fig, axes = plt.subplots(1, 3, figsize=(21, 6))\n",
    "for ax, (name, study) in zip(axes, [('XGBoost', xgb_study),\n",
    "                                     ('LightGBM', lgb_study),\n",
    "                                     ('CatBoost', cat_study)]):\n",
    "    vals = [t.value for t in study.trials if t.value is not None]\n",
    "    ax.plot(range(1, len(vals)+1), vals, 'o-', alpha=0.5, ms=5)\n",
    "    best_so_far = [max(vals[:i+1]) for i in range(len(vals))]\n",
    "    ax.plot(range(1, len(vals)+1), best_so_far, 'r-', lw=2, label='Best')\n",
    "    ax.set_xlabel('Trial'); ax.set_ylabel('AUC')\n",
    "    ax.set_title(f'{name} ({len(vals)} trials)'); ax.legend()\n",
    "plt.tight_layout()\n",
    "plt.savefig('optuna_trials.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

# ── Cell 22: Feature Importance ────────────────────────────────────────────
cells.append(code([
    "# Feature Importance — Top 20\n",
    "fig, axes = plt.subplots(1, 3, figsize=(24, 10))\n",
    "\n",
    "# XGBoost (native booster → f0, f1, ...)\n",
    "xgb_imp = xgb_bst.get_score(importance_type='gain')\n",
    "xgb_named = {}\n",
    "for k, v in xgb_imp.items():\n",
    "    idx = int(k.replace('f', ''))\n",
    "    if idx < len(feature_cols):\n",
    "        xgb_named[feature_cols[idx]] = v\n",
    "pd.Series(xgb_named).nlargest(20).plot(kind='barh', ax=axes[0], color='steelblue')\n",
    "axes[0].set_title('XGBoost — Top 20'); axes[0].set_xlabel('Gain')\n",
    "\n",
    "# LightGBM\n",
    "pd.Series(lgb_model.feature_importances_, index=feature_cols).nlargest(20).plot(\n",
    "    kind='barh', ax=axes[1], color='forestgreen')\n",
    "axes[1].set_title('LightGBM — Top 20'); axes[1].set_xlabel('Importance')\n",
    "\n",
    "# CatBoost\n",
    "pd.Series(cat_model.feature_importances_, index=feature_cols).nlargest(20).plot(\n",
    "    kind='barh', ax=axes[2], color='darkorange')\n",
    "axes[2].set_title('CatBoost — Top 20'); axes[2].set_xlabel('Importance')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('feature_importance.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

# ── Cell 23: Export ────────────────────────────────────────────────────────
cells.append(code([
    "# Save everything\n",
    "os.makedirs('improved_outputs', exist_ok=True)\n",
    "\n",
    "xgb_bst.save_model('improved_outputs/xgb_tuned.json')\n",
    "joblib.dump(lgb_model, 'improved_outputs/lgb_tuned.joblib')\n",
    "joblib.dump(cat_model, 'improved_outputs/cat_tuned.joblib')\n",
    "joblib.dump(mlp_model, 'improved_outputs/mlp_model.joblib')\n",
    "joblib.dump(meta_lr,   'improved_outputs/meta_lr_stacking.joblib')\n",
    "joblib.dump(scaler,    'improved_outputs/scaler.joblib')\n",
    "\n",
    "with open('improved_outputs/best_params.json', 'w') as f:\n",
    "    json.dump({\n",
    "        'xgb_params': xgb_study.best_params, 'xgb_cv_auc': xgb_study.best_value,\n",
    "        'lgb_params': lgb_study.best_params, 'lgb_cv_auc': lgb_study.best_value,\n",
    "        'cat_params': cat_study.best_params, 'cat_cv_auc': cat_study.best_value,\n",
    "    }, f, indent=2, default=str)\n",
    "\n",
    "rows = []\n",
    "for name, proba in {**models, **results}.items():\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ap  = average_precision_score(y_test, proba)\n",
    "    f1  = f1_score(y_test, (proba >= THRESHOLD).astype(int))\n",
    "    rows.append({'method': name, 'auc': auc, 'ap': ap, 'f1': f1})\n",
    "pd.DataFrame(rows).sort_values('auc', ascending=False).to_csv(\n",
    "    'improved_outputs/results_summary.csv', index=False)\n",
    "\n",
    "with open('improved_outputs/feature_list.txt', 'w') as f:\n",
    "    for feat in feature_cols:\n",
    "        f.write(feat + '\\n')\n",
    "\n",
    "for img in glob.glob('*.png'):\n",
    "    shutil.copy(img, f'improved_outputs/{img}')\n",
    "\n",
    "shutil.make_archive('CareAssist_Improved_Outputs', 'zip', 'improved_outputs')\n",
    "print('Created: CareAssist_Improved_Outputs.zip')"
]))

# ── Cell 24: Download ──────────────────────────────────────────────────────
cells.append(code([
    "# Download\n",
    "from google.colab import files\n",
    "files.download('CareAssist_Improved_Outputs.zip')\n",
    "print('Download started!')"
]))

# ═══════════════════════════════════════════════════════════════════════════
# Build notebook JSON
# ═══════════════════════════════════════════════════════════════════════════
notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {"provenance": [], "gpuType": "T4"},
        "kernelspec": {"name": "python3", "display_name": "Python 3"},
        "language_info": {"name": "python"},
        "accelerator": "GPU"
    },
    "cells": cells
}

workspace_dir = os.path.dirname(os.path.abspath(__file__))
output_name = "CareAssist_Improved_Model.ipynb"
path1 = os.path.join(workspace_dir, output_name)
path2 = os.path.join(os.path.expanduser("~"), "Downloads", output_name)

for path in [path1, path2]:
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=1, ensure_ascii=False)
    print(f"Wrote {path} ({os.path.getsize(path):,} bytes)")

with open(path1, 'r', encoding='utf-8') as f:
    nb = json.load(f)
print(f"\nValidation: {len(nb['cells'])} cells, nbformat={nb['nbformat']}")
print("All good!")
