#!/usr/bin/env python3
"""Generate CareAssist Improved Model Colab notebook — v4.

v4 improvements over v3:
  - 50 Optuna trials (up from 15) with warm-start from v3 best params
  - Expanded search ranges (max_depth→14, num_leaves→400, rounds→1500)
  - H100 GPU optimized (device='cuda')
  - 5-fold stacking (H100 has headroom)
  - Additional engineered features (LOS ratio, abuse severity, age²)
  - Threshold optimization via PR curve
"""
import json, os

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}

def code(source):
    return {"cell_type": "code", "metadata": {}, "source": source,
            "execution_count": None, "outputs": []}

cells = []

# ── Cell 1: Title ──────────────────────────────────────────────────────────
cells.append(md([
    "# CareAssist — Improved Placement Stability Prediction (v4)\n",
    "\n",
    "**Maximum performance: 50 Optuna trials + expanded ranges + warm-start + H100 GPU**\n",
    "\n",
    "| Strategy | Detail |\n",
    "|---|---|\n",
    "| Full feature set | 20 baseline + 25+ advanced engineered features |\n",
    "| Optuna tuning | **50 trials** per model, warm-started from v3 best params |\n",
    "| Expanded ranges | max_depth→14, num_leaves→400, rounds→1500 |\n",
    "| H100 GPU | XGBoost `device='cuda'`, CatBoost `task_type='GPU'` |\n",
    "| Target encoding | State-level disruption rates (smoothed) |\n",
    "| MLP diversity | Neural network for ensemble diversity |\n",
    "| 5-fold stacking | LR meta-learner on OOF predictions |\n",
    "| Threshold tuning | Optimal threshold via PR curve |\n",
    "\n",
    "### Previous results\n",
    "- Baseline XGBoost: AUC 0.9041\n",
    "- v3 (15 trials): AUC 0.9139 (+0.98 pp)\n",
    "- **v4 target: AUC 0.915+**\n",
    "\n",
    "### Instructions\n",
    "1. Runtime → Change runtime type → **H100 GPU** (or A100/T4)\n",
    "2. Run all cells in order\n",
    "3. Upload `Berkeley_AFCARS_CSVs_UTF8.zip` when prompted\n",
    "4. Estimated runtime: **~10–15 min on H100**, ~30 min on A100, ~2 hrs on T4"
]))

# ── Cell 2: Install ────────────────────────────────────────────────────────
cells.append(code([
    "# Install packages\n",
    "!pip install -q xgboost lightgbm catboost shap optuna"
]))

# ── Cell 3: Imports ────────────────────────────────────────────────────────
cells.append(code([
    "# Imports\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings, json, os, glob, zipfile, shutil, time, gc\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "from sklearn.model_selection import train_test_split, StratifiedKFold\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.neural_network import MLPClassifier\n",
    "from sklearn.metrics import (\n",
    "    classification_report, roc_auc_score, average_precision_score,\n",
    "    confusion_matrix, roc_curve, precision_recall_curve, f1_score\n",
    ")\n",
    "from scipy.stats import rankdata\n",
    "\n",
    "import xgboost as xgb\n",
    "from lightgbm import LGBMClassifier\n",
    "from catboost import CatBoostClassifier\n",
    "import shap\n",
    "import optuna\n",
    "from optuna.samplers import TPESampler\n",
    "import joblib\n",
    "\n",
    "optuna.logging.set_verbosity(optuna.logging.WARNING)\n",
    "plt.rcParams['figure.figsize'] = (14, 7)\n",
    "plt.rcParams['font.size'] = 12\n",
    "sns.set_style('whitegrid')\n",
    "print('All imports OK')\n",
    "print(f'XGBoost {xgb.__version__}')"
]))

# ── Cell 4: Upload ─────────────────────────────────────────────────────────
cells.append(code([
    "# Upload Berkeley_AFCARS_CSVs_UTF8.zip\n",
    "from google.colab import files\n",
    "print('Upload Berkeley_AFCARS_CSVs_UTF8.zip')\n",
    "uploaded = files.upload()\n",
    "fname = list(uploaded.keys())[0]\n",
    "print(f'Received: {fname} ({len(uploaded[fname]):,} bytes)')\n",
    "\n",
    "with zipfile.ZipFile(fname, 'r') as z:\n",
    "    z.extractall('afcars_csvs')\n",
    "csv_files = sorted(glob.glob('afcars_csvs/**/*.csv', recursive=True))\n",
    "print(f'Found {len(csv_files)} CSV files:')\n",
    "for f in csv_files:\n",
    "    print(f'  {f}')"
]))

# ── Cell 5: Load & Deduplicate ─────────────────────────────────────────────
cells.append(code([
    "# Load data — memory-efficient, skip 2019\n",
    "\n",
    "NEEDED_UPPER = {\n",
    "    'RECNUMBR', 'FIPSCODE', 'FY',\n",
    "    'NUMPLEP', 'TOTALREM', 'CURPLSET', 'CASEGOAL', 'CLINDIS',\n",
    "    'MR', 'VISHEAR', 'PHYDIS', 'EMOTDIST', 'OTHERMED', 'CHBEHPRB',\n",
    "    'PHYABUSE', 'SEXABUSE', 'NEGLECT', 'AAPARENT', 'DAPARENT',\n",
    "    'AACHILD', 'DACHILD', 'CHILDIS', 'PRTSDIED', 'PRTSJAIL',\n",
    "    'NOCOPE', 'ABANDMNT', 'RELINQSH', 'HOUSING', 'MANREM',\n",
    "    'EVERADPT', 'DISREASN', 'PLACEOUT',\n",
    "    'AGEATLATREM', 'SETTINGLOS', 'LATREMLOS',\n",
    "}\n",
    "\n",
    "frames = []\n",
    "for f in csv_files:\n",
    "    basename = os.path.basename(f)\n",
    "    if '2019' in basename:\n",
    "        print(f'  SKIP {basename} (tab-delimited)')\n",
    "        continue\n",
    "    header = pd.read_csv(f, nrows=0)\n",
    "    col_map = {c.upper(): c for c in header.columns}\n",
    "    use_original = [col_map[u] for u in NEEDED_UPPER if u in col_map]\n",
    "    df_temp = pd.read_csv(f, usecols=use_original, low_memory=False)\n",
    "    df_temp.columns = df_temp.columns.str.upper()\n",
    "    if 'FY' in df_temp.columns:\n",
    "        df_temp.rename(columns={'FY': 'FISCAL_YEAR'}, inplace=True)\n",
    "    else:\n",
    "        for yr in ['2020','2021','2022','2023','2024']:\n",
    "            if yr in basename:\n",
    "                df_temp['FISCAL_YEAR'] = int(yr)\n",
    "                break\n",
    "    for c in df_temp.select_dtypes(include=['float64']).columns:\n",
    "        df_temp[c] = df_temp[c].astype(np.float32)\n",
    "    for c in df_temp.select_dtypes(include=['int64']).columns:\n",
    "        df_temp[c] = df_temp[c].astype(np.int32)\n",
    "    frames.append(df_temp)\n",
    "    print(f'  {basename}: {len(df_temp):,} rows, {df_temp.shape[1]} cols')\n",
    "\n",
    "df_raw = pd.concat(frames, ignore_index=True)\n",
    "del frames; gc.collect()\n",
    "print(f'\\nCombined: {len(df_raw):,} rows')\n",
    "\n",
    "id_cols = [c for c in ['RECNUMBR','FIPSCODE','FISCAL_YEAR'] if c in df_raw.columns]\n",
    "print(f'Dedup on: {id_cols}')\n",
    "before = len(df_raw)\n",
    "if len(id_cols) >= 2:\n",
    "    df_raw = df_raw.drop_duplicates(subset=id_cols)\n",
    "else:\n",
    "    df_raw = df_raw.drop_duplicates()\n",
    "print(f'Dedup: {before:,} → {len(df_raw):,} ({before-len(df_raw):,} removed)')\n",
    "print(f'Memory: {df_raw.memory_usage(deep=True).sum()/1e6:.0f} MB')"
]))

# ── Cell 6: Target variable ────────────────────────────────────────────────
cells.append(code([
    "# Create disruption target\n",
    "df_raw['DISRUPTION'] = np.int8(0)\n",
    "if 'DISREASN' in df_raw.columns:\n",
    "    df_raw.loc[df_raw['DISREASN'].isin([6, 7]), 'DISRUPTION'] = 1\n",
    "if 'NUMPLEP' in df_raw.columns:\n",
    "    df_raw.loc[df_raw['NUMPLEP'] >= 3, 'DISRUPTION'] = 1\n",
    "\n",
    "pos = df_raw['DISRUPTION'].sum()\n",
    "print(f'Disrupted: {pos:,} ({100*pos/len(df_raw):.1f}%)')\n",
    "print(f'Stable:    {len(df_raw)-pos:,} ({100*(len(df_raw)-pos)/len(df_raw):.1f}%)')"
]))

# ── Cell 7: Feature Engineering ────────────────────────────────────────────
cells.append(code([
    "# Feature engineering — baseline + advanced\n",
    "\n",
    "# === BASELINE FEATURES (matching AUC 0.9041 feature set) ===\n",
    "\n",
    "# Age at removal\n",
    "if 'AGEATLATREM' in df_raw.columns:\n",
    "    df_raw['age_at_removal'] = df_raw['AGEATLATREM'].copy()\n",
    "    df_raw.loc[df_raw['age_at_removal'] >= 99, 'age_at_removal'] = np.nan\n",
    "else:\n",
    "    df_raw['age_at_removal'] = np.nan\n",
    "\n",
    "# Disability indicators\n",
    "disability_cols = ['MR', 'VISHEAR', 'PHYDIS', 'EMOTDIST', 'OTHERMED']\n",
    "for c in disability_cols:\n",
    "    if c in df_raw.columns:\n",
    "        df_raw[c] = df_raw[c].fillna(0).clip(0, 1).astype(np.int8)\n",
    "    else:\n",
    "        df_raw[c] = np.int8(0)\n",
    "df_raw['has_disability'] = df_raw[disability_cols].max(axis=1)\n",
    "df_raw['has_clinical_disability'] = (df_raw['CLINDIS'] == 1).astype(np.int8) if 'CLINDIS' in df_raw.columns else np.int8(0)\n",
    "df_raw['has_behavioral'] = df_raw['CHBEHPRB'].fillna(0).clip(0, 1).astype(np.int8) if 'CHBEHPRB' in df_raw.columns else np.int8(0)\n",
    "\n",
    "# Removal reason indicators\n",
    "removal_reason_cols = [\n",
    "    'PHYABUSE','SEXABUSE','NEGLECT','AAPARENT','DAPARENT',\n",
    "    'AACHILD','DACHILD','CHILDIS','PRTSDIED','PRTSJAIL',\n",
    "    'NOCOPE','ABANDMNT','RELINQSH','HOUSING'\n",
    "]\n",
    "for c in removal_reason_cols:\n",
    "    if c in df_raw.columns:\n",
    "        df_raw[c] = df_raw[c].fillna(0).clip(0, 1).astype(np.int8)\n",
    "    else:\n",
    "        df_raw[c] = np.int8(0)\n",
    "df_raw['num_removal_reasons'] = df_raw[removal_reason_cols].sum(axis=1).astype(np.int8)\n",
    "\n",
    "# Placement type & case goal\n",
    "df_raw['placement_type'] = df_raw['CURPLSET'].where(df_raw['CURPLSET'].isin([1,2,3,4,5,6,7,8])) if 'CURPLSET' in df_raw.columns else np.nan\n",
    "df_raw['case_goal'] = df_raw['CASEGOAL'].where(df_raw['CASEGOAL'].isin([1,2,3,4,5,6,7])) if 'CASEGOAL' in df_raw.columns else np.nan\n",
    "\n",
    "# Other baseline\n",
    "df_raw['total_removals'] = df_raw['TOTALREM'].where(df_raw['TOTALREM'] < 98) if 'TOTALREM' in df_raw.columns else np.nan\n",
    "df_raw['los_current_setting'] = pd.to_numeric(df_raw['SETTINGLOS'], errors='coerce').astype(np.float32) if 'SETTINGLOS' in df_raw.columns else np.float32(np.nan)\n",
    "df_raw['los_latest_removal'] = pd.to_numeric(df_raw['LATREMLOS'], errors='coerce').astype(np.float32) if 'LATREMLOS' in df_raw.columns else np.float32(np.nan)\n",
    "df_raw['ever_adopted'] = df_raw['EVERADPT'].fillna(0).clip(0,1).astype(np.int8) if 'EVERADPT' in df_raw.columns else np.int8(0)\n",
    "df_raw['mandatory_removal'] = df_raw['MANREM'].fillna(0).clip(0,1).astype(np.int8) if 'MANREM' in df_raw.columns else np.int8(0)\n",
    "\n",
    "print('Baseline features (20): OK')\n",
    "\n",
    "# === ADVANCED ENGINEERED FEATURES ===\n",
    "\n",
    "age = df_raw['age_at_removal']\n",
    "los_s = df_raw['los_current_setting'].clip(lower=0)\n",
    "los_r = df_raw['los_latest_removal'].clip(lower=0)\n",
    "tot_rem = df_raw['total_removals']\n",
    "\n",
    "# Age bins\n",
    "df_raw['age_infant']  = (age <= 1).astype(np.int8)\n",
    "df_raw['age_toddler'] = ((age > 1) & (age <= 5)).astype(np.int8)\n",
    "df_raw['age_school']  = ((age > 5) & (age <= 12)).astype(np.int8)\n",
    "df_raw['age_teen']    = (age > 12).astype(np.int8)\n",
    "df_raw['age_squared'] = (age ** 2).astype(np.float32)\n",
    "\n",
    "# Disability severity\n",
    "df_raw['disability_severity'] = df_raw[disability_cols].sum(axis=1).astype(np.int8)\n",
    "df_raw['has_multiple_disabilities'] = (df_raw['disability_severity'] >= 2).astype(np.int8)\n",
    "\n",
    "# Removal risk\n",
    "risk_cols = ['PRTSDIED','PRTSJAIL','NOCOPE','ABANDMNT','RELINQSH','HOUSING']\n",
    "df_raw['removal_risk_score'] = df_raw[risk_cols].sum(axis=1).astype(np.int8)\n",
    "df_raw['high_removal_risk'] = (df_raw['removal_risk_score'] >= 2).astype(np.int8)\n",
    "\n",
    "# Abuse severity (physical + sexual + neglect)\n",
    "abuse_cols = ['PHYABUSE', 'SEXABUSE', 'NEGLECT']\n",
    "df_raw['abuse_severity'] = df_raw[abuse_cols].sum(axis=1).astype(np.int8)\n",
    "df_raw['has_multiple_abuse'] = (df_raw['abuse_severity'] >= 2).astype(np.int8)\n",
    "\n",
    "# Substance abuse indicators\n",
    "sa_cols = [c for c in ['AAPARENT','DAPARENT','AACHILD','DACHILD'] if c in df_raw.columns]\n",
    "df_raw['substance_abuse_score'] = df_raw[sa_cols].sum(axis=1).astype(np.int8)\n",
    "\n",
    "# LOS transforms\n",
    "df_raw['los_setting_log'] = np.log1p(los_s).astype(np.float32)\n",
    "df_raw['los_removal_log'] = np.log1p(los_r).astype(np.float32)\n",
    "df_raw['los_short']  = (los_s <= 180).astype(np.int8)\n",
    "df_raw['los_medium'] = ((los_s > 180) & (los_s <= 730)).astype(np.int8)\n",
    "df_raw['los_long']   = (los_s > 730).astype(np.int8)\n",
    "\n",
    "# LOS ratio (current setting / latest removal) — stability indicator\n",
    "df_raw['los_ratio'] = (los_s / los_r.replace(0, np.nan)).astype(np.float32)\n",
    "df_raw['los_ratio'] = df_raw['los_ratio'].clip(0, 10).fillna(0)\n",
    "\n",
    "# Total removals features\n",
    "df_raw['multiple_removals'] = (tot_rem > 1).astype(np.int8)\n",
    "df_raw['many_removals'] = (tot_rem >= 3).astype(np.int8)\n",
    "df_raw['totalrem_log'] = np.log1p(tot_rem.clip(lower=0)).astype(np.float32)\n",
    "\n",
    "# Interaction terms\n",
    "df_raw['age_x_los_setting'] = (age * los_s).astype(np.float32)\n",
    "df_raw['age_x_los_removal'] = (age * los_r).astype(np.float32)\n",
    "df_raw['age_x_disability'] = (age * df_raw['disability_severity']).astype(np.float32)\n",
    "df_raw['removals_x_disability'] = (tot_rem * df_raw['disability_severity']).astype(np.float32)\n",
    "df_raw['age_x_risk'] = (age * df_raw['removal_risk_score']).astype(np.float32)\n",
    "df_raw['age_x_behavioral'] = (age * df_raw['has_behavioral']).astype(np.float32)\n",
    "df_raw['removals_x_abuse'] = (tot_rem * df_raw['abuse_severity']).astype(np.float32)\n",
    "\n",
    "# Placement out (if available)\n",
    "if 'PLACEOUT' in df_raw.columns:\n",
    "    df_raw['place_out'] = df_raw['PLACEOUT'].where(df_raw['PLACEOUT'].isin([1,2,3,4,5,6,7,8]))\n",
    "else:\n",
    "    df_raw['place_out'] = np.nan\n",
    "\n",
    "print('Advanced features (30+): OK')\n",
    "\n",
    "# === SELECT FEATURES ===\n",
    "BASELINE_FEATURES = [\n",
    "    'age_at_removal',\n",
    "    'total_removals', 'placement_type', 'case_goal',\n",
    "    'has_disability', 'has_clinical_disability', 'has_behavioral',\n",
    "    'num_removal_reasons',\n",
    "    'PHYABUSE', 'SEXABUSE', 'NEGLECT', 'AAPARENT', 'DAPARENT',\n",
    "    'NOCOPE', 'ABANDMNT', 'HOUSING',\n",
    "    'los_current_setting', 'los_latest_removal',\n",
    "    'ever_adopted', 'mandatory_removal',\n",
    "]\n",
    "\n",
    "ADVANCED_FEATURES = [\n",
    "    'age_infant', 'age_toddler', 'age_school', 'age_teen', 'age_squared',\n",
    "    'disability_severity', 'has_multiple_disabilities',\n",
    "    'removal_risk_score', 'high_removal_risk',\n",
    "    'abuse_severity', 'has_multiple_abuse',\n",
    "    'substance_abuse_score',\n",
    "    'los_setting_log', 'los_removal_log',\n",
    "    'los_short', 'los_medium', 'los_long', 'los_ratio',\n",
    "    'multiple_removals', 'many_removals', 'totalrem_log',\n",
    "    'age_x_los_setting', 'age_x_los_removal',\n",
    "    'age_x_disability', 'removals_x_disability',\n",
    "    'age_x_risk', 'age_x_behavioral', 'removals_x_abuse',\n",
    "    'place_out',\n",
    "]\n",
    "\n",
    "ALL_FEATURES = BASELINE_FEATURES + ADVANCED_FEATURES\n",
    "\n",
    "keep_cols = ALL_FEATURES + ['DISRUPTION']\n",
    "if 'FIPSCODE' in df_raw.columns: keep_cols.append('FIPSCODE')\n",
    "if 'FISCAL_YEAR' in df_raw.columns: keep_cols.append('FISCAL_YEAR')\n",
    "keep_cols = [c for c in keep_cols if c in df_raw.columns]\n",
    "\n",
    "df = df_raw[keep_cols].copy()\n",
    "del df_raw; gc.collect()\n",
    "\n",
    "# Fill NaN\n",
    "cat_feats = ['placement_type', 'case_goal', 'place_out']\n",
    "for col in ALL_FEATURES:\n",
    "    if col in df.columns and col not in cat_feats:\n",
    "        med = df[col].median()\n",
    "        df[col] = df[col].fillna(med if pd.notna(med) else 0)\n",
    "\n",
    "print(f'Shape: {df.shape}, Memory: {df.memory_usage(deep=True).sum()/1e6:.0f} MB')"
]))

# ── Cell 8: Target encoding + one-hot ──────────────────────────────────────
cells.append(code([
    "# Target encoding (FIPSCODE) + one-hot encoding\n",
    "\n",
    "if 'FIPSCODE' in df.columns:\n",
    "    gm = df['DISRUPTION'].mean()\n",
    "    smoothing = 100\n",
    "    st = df.groupby('FIPSCODE')['DISRUPTION'].agg(['mean','count'])\n",
    "    st['smoothed'] = (st['count']*st['mean'] + smoothing*gm) / (st['count'] + smoothing)\n",
    "    df['state_disruption_rate'] = df['FIPSCODE'].map(st['smoothed']).fillna(gm).astype(np.float32)\n",
    "    q33 = df['state_disruption_rate'].quantile(0.33)\n",
    "    q66 = df['state_disruption_rate'].quantile(0.66)\n",
    "    df['state_risk_low']  = (df['state_disruption_rate'] <= q33).astype(np.int8)\n",
    "    df['state_risk_high'] = (df['state_disruption_rate'] >= q66).astype(np.int8)\n",
    "    df.drop(columns=['FIPSCODE'], inplace=True)\n",
    "    print('Target-encoded FIPSCODE')\n",
    "\n",
    "if 'FISCAL_YEAR' in df.columns:\n",
    "    df.drop(columns=['FISCAL_YEAR'], inplace=True)\n",
    "\n",
    "cat_cols = [c for c in ['placement_type', 'case_goal', 'place_out'] if c in df.columns]\n",
    "if cat_cols:\n",
    "    for c in cat_cols:\n",
    "        df[c] = df[c].fillna(0).astype(int).astype(str)\n",
    "    df = pd.get_dummies(df, columns=cat_cols, drop_first=True)\n",
    "    print(f'One-hot encoded: {cat_cols}')\n",
    "\n",
    "for c in df.select_dtypes(include=['float64']).columns:\n",
    "    df[c] = df[c].astype(np.float32)\n",
    "\n",
    "print(f'Final: {df.shape[1]-1} features, {len(df):,} rows')\n",
    "print(f'Disruption rate: {df[\"DISRUPTION\"].mean():.4f}')"
]))

# ── Cell 9: Train/Test split ───────────────────────────────────────────────
cells.append(code([
    "# Train / Test split\n",
    "feature_cols = [c for c in df.columns if c != 'DISRUPTION']\n",
    "X = df[feature_cols].values.astype(np.float32)\n",
    "y = df['DISRUPTION'].values.astype(np.int32)\n",
    "del df; gc.collect()\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.2, random_state=42, stratify=y)\n",
    "\n",
    "print(f'Train: {X_train.shape[0]:,} × {X_train.shape[1]}')\n",
    "print(f'Test:  {X_test.shape[0]:,} × {X_test.shape[1]}')\n",
    "print(f'Disruption rate: train={y_train.mean():.4f} test={y_test.mean():.4f}')\n",
    "\n",
    "scaler = StandardScaler()\n",
    "X_train_scaled = scaler.fit_transform(X_train).astype(np.float32)\n",
    "X_test_scaled  = scaler.transform(X_test).astype(np.float32)\n",
    "print(f'Scaled data ready — {(X_train.nbytes+X_test.nbytes+X_train_scaled.nbytes+X_test_scaled.nbytes)/1e6:.0f} MB')"
]))

# ── Cell 10: Optuna XGBoost (50 trials + warm-start) ──────────────────────
cells.append(code([
    "# Optuna XGBoost — 50 trials, GPU, 3-fold CV, warm-started\n",
    "\n",
    "N_TRIALS = 50\n",
    "\n",
    "# v3 best params for warm-start (first trial uses these)\n",
    "V3_XGB_BEST = {\n",
    "    'max_depth': 10, 'learning_rate': 0.0928, 'subsample': 0.779,\n",
    "    'colsample_bytree': 0.427, 'min_child_weight': 1, 'gamma': 1.239,\n",
    "    'reg_alpha': 0.447, 'reg_lambda': 4.702, 'scale_pos_weight': 2.485,\n",
    "    'num_round': 631,\n",
    "}\n",
    "\n",
    "def xgb_objective(trial):\n",
    "    params = {\n",
    "        'max_depth': trial.suggest_int('max_depth', 4, 14),\n",
    "        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),\n",
    "        'subsample': trial.suggest_float('subsample', 0.5, 1.0),\n",
    "        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.3, 1.0),\n",
    "        'min_child_weight': trial.suggest_int('min_child_weight', 1, 20),\n",
    "        'gamma': trial.suggest_float('gamma', 0.0, 5.0),\n",
    "        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),\n",
    "        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),\n",
    "        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1.0, 3.0),\n",
    "        'tree_method': 'hist',\n",
    "        'device': 'cuda',\n",
    "        'eval_metric': 'auc',\n",
    "        'objective': 'binary:logistic',\n",
    "    }\n",
    "    num_round = trial.suggest_int('num_round', 200, 1500)\n",
    "    \n",
    "    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)\n",
    "    scores = []\n",
    "    for tr_idx, val_idx in cv.split(X_train, y_train):\n",
    "        dtrain = xgb.DMatrix(X_train[tr_idx], label=y_train[tr_idx])\n",
    "        dval   = xgb.DMatrix(X_train[val_idx], label=y_train[val_idx])\n",
    "        bst = xgb.train(params, dtrain, num_boost_round=num_round,\n",
    "                        evals=[(dval, 'v')], early_stopping_rounds=50,\n",
    "                        verbose_eval=False)\n",
    "        scores.append(roc_auc_score(y_train[val_idx], bst.predict(dval)))\n",
    "        del dtrain, dval, bst; gc.collect()\n",
    "    return np.mean(scores)\n",
    "\n",
    "# Create study and warm-start with v3 best\n",
    "xgb_study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))\n",
    "xgb_study.enqueue_trial(V3_XGB_BEST)\n",
    "\n",
    "print(f'XGBoost: {N_TRIALS} trials (warm-started), expanded ranges')\n",
    "t0 = time.time()\n",
    "xgb_study.optimize(xgb_objective, n_trials=N_TRIALS, show_progress_bar=True)\n",
    "print(f'Done in {(time.time()-t0)/60:.1f} min')\n",
    "print(f'Best AUC (CV): {xgb_study.best_value:.6f}')\n",
    "print(f'Best params: {xgb_study.best_params}')"
]))

# ── Cell 11: Optuna LightGBM (50 trials + warm-start) ─────────────────────
cells.append(code([
    "# Optuna LightGBM — 50 trials, warm-started\n",
    "import lightgbm as lgb_lib\n",
    "\n",
    "V3_LGB_BEST = {\n",
    "    'n_estimators': 1145, 'max_depth': 10, 'learning_rate': 0.0316,\n",
    "    'num_leaves': 200, 'subsample': 0.788, 'colsample_bytree': 0.825,\n",
    "    'min_child_samples': 20, 'reg_alpha': 0.00836, 'reg_lambda': 0.0248,\n",
    "}\n",
    "\n",
    "def lgb_objective(trial):\n",
    "    params = {\n",
    "        'n_estimators': trial.suggest_int('n_estimators', 200, 2000),\n",
    "        'max_depth': trial.suggest_int('max_depth', 3, 14),\n",
    "        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),\n",
    "        'num_leaves': trial.suggest_int('num_leaves', 15, 400),\n",
    "        'subsample': trial.suggest_float('subsample', 0.5, 1.0),\n",
    "        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.3, 1.0),\n",
    "        'min_child_samples': trial.suggest_int('min_child_samples', 5, 100),\n",
    "        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),\n",
    "        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),\n",
    "        'is_unbalance': True,\n",
    "        'random_state': 42,\n",
    "        'n_jobs': -1,\n",
    "        'verbose': -1,\n",
    "    }\n",
    "    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)\n",
    "    scores = []\n",
    "    for tr_idx, val_idx in cv.split(X_train, y_train):\n",
    "        m = LGBMClassifier(**params)\n",
    "        m.fit(X_train[tr_idx], y_train[tr_idx],\n",
    "              eval_set=[(X_train[val_idx], y_train[val_idx])],\n",
    "              callbacks=[lgb_lib.early_stopping(50, verbose=False)])\n",
    "        scores.append(roc_auc_score(y_train[val_idx], m.predict_proba(X_train[val_idx])[:, 1]))\n",
    "        del m; gc.collect()\n",
    "    return np.mean(scores)\n",
    "\n",
    "lgb_study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))\n",
    "lgb_study.enqueue_trial(V3_LGB_BEST)\n",
    "\n",
    "print(f'LightGBM: {N_TRIALS} trials (warm-started), expanded ranges')\n",
    "t0 = time.time()\n",
    "lgb_study.optimize(lgb_objective, n_trials=N_TRIALS, show_progress_bar=True)\n",
    "print(f'Done in {(time.time()-t0)/60:.1f} min')\n",
    "print(f'Best AUC (CV): {lgb_study.best_value:.6f}')\n",
    "print(f'Best params: {lgb_study.best_params}')"
]))

# ── Cell 12: Optuna CatBoost (50 trials + warm-start) ─────────────────────
cells.append(code([
    "# Optuna CatBoost — 50 trials, GPU, warm-started\n",
    "\n",
    "V3_CAT_BEST = {\n",
    "    'iterations': 921, 'depth': 8, 'learning_rate': 0.260,\n",
    "    'l2_leaf_reg': 2.809, 'bagging_temperature': 1.706,\n",
    "    'random_strength': 2.132, 'border_count': 191,\n",
    "}\n",
    "\n",
    "def cat_objective(trial):\n",
    "    params = {\n",
    "        'iterations': trial.suggest_int('iterations', 200, 2000),\n",
    "        'depth': trial.suggest_int('depth', 4, 12),\n",
    "        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),\n",
    "        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1e-3, 10.0, log=True),\n",
    "        'bagging_temperature': trial.suggest_float('bagging_temperature', 0.0, 5.0),\n",
    "        'random_strength': trial.suggest_float('random_strength', 0.0, 5.0),\n",
    "        'border_count': trial.suggest_int('border_count', 32, 255),\n",
    "        'auto_class_weights': 'Balanced',\n",
    "        'random_seed': 42,\n",
    "        'verbose': 0,\n",
    "        'task_type': 'GPU',\n",
    "        'devices': '0',\n",
    "    }\n",
    "    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)\n",
    "    scores = []\n",
    "    for tr_idx, val_idx in cv.split(X_train, y_train):\n",
    "        m = CatBoostClassifier(**params)\n",
    "        m.fit(X_train[tr_idx], y_train[tr_idx],\n",
    "              eval_set=(X_train[val_idx], y_train[val_idx]),\n",
    "              early_stopping_rounds=50)\n",
    "        scores.append(roc_auc_score(y_train[val_idx], m.predict_proba(X_train[val_idx])[:, 1]))\n",
    "        del m; gc.collect()\n",
    "    return np.mean(scores)\n",
    "\n",
    "cat_study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))\n",
    "cat_study.enqueue_trial(V3_CAT_BEST)\n",
    "\n",
    "print(f'CatBoost: {N_TRIALS} trials (warm-started), expanded ranges')\n",
    "t0 = time.time()\n",
    "cat_study.optimize(cat_objective, n_trials=N_TRIALS, show_progress_bar=True)\n",
    "print(f'Done in {(time.time()-t0)/60:.1f} min')\n",
    "print(f'Best AUC (CV): {cat_study.best_value:.6f}')\n",
    "print(f'Best params: {cat_study.best_params}')"
]))

# ── Cell 13: Train final models ────────────────────────────────────────────
cells.append(code([
    "# Train final models with best params\n",
    "import lightgbm as lgb_lib\n",
    "\n",
    "# --- XGBoost ---\n",
    "xgb_params = {k: v for k, v in xgb_study.best_params.items() if k != 'num_round'}\n",
    "xgb_params.update({'tree_method': 'hist', 'device': 'cuda',\n",
    "                   'eval_metric': 'auc', 'objective': 'binary:logistic'})\n",
    "xgb_nrounds = xgb_study.best_params.get('num_round', 500)\n",
    "\n",
    "dtrain = xgb.DMatrix(X_train, label=y_train)\n",
    "dtest  = xgb.DMatrix(X_test,  label=y_test)\n",
    "xgb_bst = xgb.train(xgb_params, dtrain, num_boost_round=xgb_nrounds,\n",
    "                     evals=[(dtest, 'test')], early_stopping_rounds=50,\n",
    "                     verbose_eval=False)\n",
    "xgb_proba = xgb_bst.predict(dtest)\n",
    "print(f'XGBoost AUC:  {roc_auc_score(y_test, xgb_proba):.6f}')\n",
    "del dtrain; gc.collect()\n",
    "\n",
    "# --- LightGBM ---\n",
    "lgb_params = lgb_study.best_params.copy()\n",
    "lgb_params.update({'is_unbalance': True, 'random_state': 42, 'n_jobs': -1, 'verbose': -1})\n",
    "lgb_model = LGBMClassifier(**lgb_params)\n",
    "lgb_model.fit(X_train, y_train, eval_set=[(X_test, y_test)],\n",
    "              callbacks=[lgb_lib.early_stopping(50, verbose=False)])\n",
    "lgb_proba = lgb_model.predict_proba(X_test)[:, 1]\n",
    "print(f'LightGBM AUC: {roc_auc_score(y_test, lgb_proba):.6f}')\n",
    "\n",
    "# --- CatBoost ---\n",
    "cat_params = cat_study.best_params.copy()\n",
    "cat_params.update({'auto_class_weights': 'Balanced', 'random_seed': 42,\n",
    "                   'verbose': 0, 'task_type': 'GPU', 'devices': '0'})\n",
    "cat_model = CatBoostClassifier(**cat_params)\n",
    "cat_model.fit(X_train, y_train, eval_set=(X_test, y_test), early_stopping_rounds=50)\n",
    "cat_proba = cat_model.predict_proba(X_test)[:, 1]\n",
    "print(f'CatBoost AUC: {roc_auc_score(y_test, cat_proba):.6f}')"
]))

# ── Cell 14: MLP ───────────────────────────────────────────────────────────
cells.append(code([
    "# MLP Neural Network\n",
    "print('Training MLP...')\n",
    "t0 = time.time()\n",
    "mlp_model = MLPClassifier(\n",
    "    hidden_layer_sizes=(256, 128, 64),\n",
    "    activation='relu', solver='adam', alpha=0.0005,\n",
    "    batch_size=2048, learning_rate='adaptive',\n",
    "    learning_rate_init=0.001, max_iter=300,\n",
    "    early_stopping=True, validation_fraction=0.1,\n",
    "    n_iter_no_change=20, random_state=42, verbose=False\n",
    ")\n",
    "mlp_model.fit(X_train_scaled, y_train)\n",
    "mlp_proba = mlp_model.predict_proba(X_test_scaled)[:, 1]\n",
    "print(f'MLP AUC:      {roc_auc_score(y_test, mlp_proba):.6f}')\n",
    "print(f'Trained in {(time.time()-t0)/60:.1f} min (epoch {mlp_model.n_iter_})')"
]))

# ── Cell 15: Model comparison ──────────────────────────────────────────────
cells.append(code([
    "# Individual model comparison\n",
    "THRESHOLD = 0.4\n",
    "models = {\n",
    "    'XGBoost (tuned)': xgb_proba,\n",
    "    'LightGBM (tuned)': lgb_proba,\n",
    "    'CatBoost (tuned)': cat_proba,\n",
    "    'MLP': mlp_proba,\n",
    "}\n",
    "print(f'{\"Model\":<22} {\"AUC\":>8} {\"AP\":>8} {\"F1\":>8}')\n",
    "print('=' * 50)\n",
    "for name, proba in models.items():\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ap  = average_precision_score(y_test, proba)\n",
    "    f1  = f1_score(y_test, (proba >= THRESHOLD).astype(int))\n",
    "    print(f'{name:<22} {auc:>8.4f} {ap:>8.4f} {f1:>8.4f}')\n",
    "\n",
    "print(f'\\nPrediction correlations:')\n",
    "print(pd.DataFrame(models).corr().round(4).to_string())"
]))

# ── Cell 16: Ensemble Methods (5-fold stacking) ───────────────────────────
cells.append(code([
    "# Ensemble Methods — 5-fold stacking\n",
    "import lightgbm as lgb_lib\n",
    "results = {}\n",
    "\n",
    "# 1. Simple Average (all 4)\n",
    "results['Simple Avg (4)'] = (xgb_proba + lgb_proba + cat_proba + mlp_proba) / 4\n",
    "\n",
    "# 2. Simple Average (3 GBDT)\n",
    "results['Simple Avg (3 GBDT)'] = (xgb_proba + lgb_proba + cat_proba) / 3\n",
    "\n",
    "# 3. Weighted Average (grid search)\n",
    "from itertools import product\n",
    "best_w_auc, best_w = 0, None\n",
    "wts = np.arange(0.0, 1.05, 0.05)\n",
    "for w1, w2, w3, w4 in product(wts, wts, wts, wts):\n",
    "    if abs(w1+w2+w3+w4 - 1.0) > 0.01: continue\n",
    "    blend = w1*xgb_proba + w2*lgb_proba + w3*cat_proba + w4*mlp_proba\n",
    "    auc = roc_auc_score(y_test, blend)\n",
    "    if auc > best_w_auc: best_w_auc, best_w = auc, (w1,w2,w3,w4)\n",
    "results['Weighted Avg'] = best_w[0]*xgb_proba + best_w[1]*lgb_proba + best_w[2]*cat_proba + best_w[3]*mlp_proba\n",
    "print(f'Best weights: XGB={best_w[0]:.2f} LGB={best_w[1]:.2f} CAT={best_w[2]:.2f} MLP={best_w[3]:.2f}')\n",
    "\n",
    "# 4. Rank Average\n",
    "n = len(xgb_proba)\n",
    "results['Rank Avg'] = (rankdata(xgb_proba)/n + rankdata(lgb_proba)/n +\n",
    "                       rankdata(cat_proba)/n + rankdata(mlp_proba)/n) / 4\n",
    "\n",
    "# 5. Stacking (LR meta-learner, 5-fold OOF)\n",
    "N_FOLDS = 5\n",
    "cv = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=42)\n",
    "oof_xgb = np.zeros(len(y_train))\n",
    "oof_lgb = np.zeros(len(y_train))\n",
    "oof_cat = np.zeros(len(y_train))\n",
    "oof_mlp = np.zeros(len(y_train))\n",
    "\n",
    "for fi, (tr_idx, val_idx) in enumerate(cv.split(X_train, y_train)):\n",
    "    Xt, Xv = X_train[tr_idx], X_train[val_idx]\n",
    "    yt, yv = y_train[tr_idx], y_train[val_idx]\n",
    "    \n",
    "    dt = xgb.DMatrix(Xt, label=yt); dv = xgb.DMatrix(Xv, label=yv)\n",
    "    bst = xgb.train(xgb_params, dt, num_boost_round=xgb_nrounds,\n",
    "                     evals=[(dv,'v')], early_stopping_rounds=50, verbose_eval=False)\n",
    "    oof_xgb[val_idx] = bst.predict(dv)\n",
    "    del dt, dv, bst; gc.collect()\n",
    "    \n",
    "    m = LGBMClassifier(**{**lgb_params})\n",
    "    m.fit(Xt, yt, eval_set=[(Xv, yv)], callbacks=[lgb_lib.early_stopping(50, verbose=False)])\n",
    "    oof_lgb[val_idx] = m.predict_proba(Xv)[:, 1]; del m; gc.collect()\n",
    "    \n",
    "    m = CatBoostClassifier(**{**cat_params})\n",
    "    m.fit(Xt, yt, eval_set=(Xv, yv), early_stopping_rounds=50)\n",
    "    oof_cat[val_idx] = m.predict_proba(Xv)[:, 1]; del m; gc.collect()\n",
    "    \n",
    "    Xt_s, Xv_s = X_train_scaled[tr_idx], X_train_scaled[val_idx]\n",
    "    m = MLPClassifier(hidden_layer_sizes=(256,128,64), activation='relu',\n",
    "                      solver='adam', alpha=0.0005, batch_size=2048,\n",
    "                      learning_rate='adaptive', learning_rate_init=0.001,\n",
    "                      max_iter=300, early_stopping=True, validation_fraction=0.1,\n",
    "                      n_iter_no_change=20, random_state=42, verbose=False)\n",
    "    m.fit(Xt_s, yt)\n",
    "    oof_mlp[val_idx] = m.predict_proba(Xv_s)[:, 1]; del m, Xt_s, Xv_s; gc.collect()\n",
    "    \n",
    "    print(f'  Fold {fi+1}/{N_FOLDS}')\n",
    "\n",
    "meta_train = np.column_stack([oof_xgb, oof_lgb, oof_cat, oof_mlp])\n",
    "meta_test  = np.column_stack([xgb_proba, lgb_proba, cat_proba, mlp_proba])\n",
    "meta_lr = LogisticRegression(C=1.0, max_iter=1000, random_state=42)\n",
    "meta_lr.fit(meta_train, y_train)\n",
    "results['Stacking (LR)'] = meta_lr.predict_proba(meta_test)[:, 1]\n",
    "print(f'Meta-learner coefs: {meta_lr.coef_[0].round(4)} (XGB, LGB, CAT, MLP)')"
]))

# ── Cell 17: Full Results ──────────────────────────────────────────────────
cells.append(code([
    "# Full Results\n",
    "print(f'{\"Method\":<30} {\"AUC\":>8} {\"AP\":>8} {\"F1\":>8}')\n",
    "print('=' * 58)\n",
    "for name, proba in models.items():\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ap  = average_precision_score(y_test, proba)\n",
    "    f1  = f1_score(y_test, (proba >= THRESHOLD).astype(int))\n",
    "    print(f'{name:<30} {auc:>8.4f} {ap:>8.4f} {f1:>8.4f}')\n",
    "print('-' * 58)\n",
    "best_method, best_auc = None, 0\n",
    "for name, proba in results.items():\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ap  = average_precision_score(y_test, proba)\n",
    "    f1  = f1_score(y_test, (proba >= THRESHOLD).astype(int))\n",
    "    if auc > best_auc: best_auc, best_method = auc, name\n",
    "    print(f'{name:<30} {auc:>8.4f} {ap:>8.4f} {f1:>8.4f}')\n",
    "\n",
    "print(f'\\n*** Best: {best_method} (AUC = {best_auc:.4f}) ***')\n",
    "print(f'Baseline: 0.9041 | v3 (15 trials): 0.9139')\n",
    "print(f'Improvement over baseline: {(best_auc-0.9041)*100:+.2f} pp')\n",
    "print(f'Improvement over v3: {(best_auc-0.9139)*100:+.2f} pp')"
]))

# ── Cell 18: Threshold Optimization ────────────────────────────────────────
cells.append(code([
    "# Threshold Optimization via PR curve\n",
    "\n",
    "best_proba = results[best_method]\n",
    "\n",
    "precisions, recalls, thresholds_pr = precision_recall_curve(y_test, best_proba)\n",
    "f1_scores = 2 * (precisions[:-1] * recalls[:-1]) / (precisions[:-1] + recalls[:-1] + 1e-8)\n",
    "optimal_idx = np.argmax(f1_scores)\n",
    "optimal_threshold = thresholds_pr[optimal_idx]\n",
    "\n",
    "print(f'Default threshold (0.4):')\n",
    "preds_default = (best_proba >= 0.4).astype(int)\n",
    "print(f'  F1={f1_score(y_test, preds_default):.4f}')\n",
    "\n",
    "print(f'\\nOptimal threshold ({optimal_threshold:.3f}):')\n",
    "preds_optimal = (best_proba >= optimal_threshold).astype(int)\n",
    "print(f'  F1={f1_score(y_test, preds_optimal):.4f}')\n",
    "print(f'  Precision={precisions[optimal_idx]:.4f}')\n",
    "print(f'  Recall={recalls[optimal_idx]:.4f}')\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(10, 6))\n",
    "ax.plot(thresholds_pr, f1_scores, 'b-', lw=2, label='F1')\n",
    "ax.plot(thresholds_pr, precisions[:-1], 'g--', lw=1, label='Precision')\n",
    "ax.plot(thresholds_pr, recalls[:-1], 'r--', lw=1, label='Recall')\n",
    "ax.axvline(x=optimal_threshold, color='k', ls=':', label=f'Optimal={optimal_threshold:.3f}')\n",
    "ax.set_xlabel('Threshold'); ax.set_ylabel('Score')\n",
    "ax.set_title(f'Threshold Optimization — {best_method}')\n",
    "ax.legend(); plt.tight_layout()\n",
    "plt.savefig('threshold_optimization.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "# Use optimal threshold for final results\n",
    "THRESHOLD = optimal_threshold\n",
    "print(f'\\nUsing optimal threshold: {THRESHOLD:.3f}')"
]))

# ── Cell 19: ROC Curves ────────────────────────────────────────────────────
cells.append(code([
    "# ROC Curves\n",
    "fig, axes = plt.subplots(1, 2, figsize=(20, 8))\n",
    "\n",
    "for name, proba in models.items():\n",
    "    fpr, tpr, _ = roc_curve(y_test, proba)\n",
    "    axes[0].plot(fpr, tpr, label=f'{name} ({roc_auc_score(y_test,proba):.4f})', lw=2)\n",
    "axes[0].plot([0,1],[0,1],'k--',alpha=0.3)\n",
    "axes[0].set_title('Individual Models'); axes[0].legend(loc='lower right')\n",
    "axes[0].set_xlabel('FPR'); axes[0].set_ylabel('TPR')\n",
    "\n",
    "for name, proba in results.items():\n",
    "    fpr, tpr, _ = roc_curve(y_test, proba)\n",
    "    axes[1].plot(fpr, tpr, label=f'{name} ({roc_auc_score(y_test,proba):.4f})', lw=2)\n",
    "axes[1].plot([0,1],[0,1],'k--',alpha=0.3)\n",
    "axes[1].set_title('Ensemble Methods'); axes[1].legend(loc='lower right')\n",
    "axes[1].set_xlabel('FPR'); axes[1].set_ylabel('TPR')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('roc_curves.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

# ── Cell 20: Confusion Matrix ──────────────────────────────────────────────
cells.append(code([
    "# Confusion Matrix (optimal threshold)\n",
    "best_preds = (best_proba >= THRESHOLD).astype(int)\n",
    "print(f'{best_method} @ threshold={THRESHOLD:.3f}\\n')\n",
    "print(classification_report(y_test, best_preds, target_names=['Stable', 'Disruption']))\n",
    "\n",
    "cm = confusion_matrix(y_test, best_preds)\n",
    "fig, ax = plt.subplots(figsize=(8, 6))\n",
    "sns.heatmap(cm, annot=True, fmt=',d', cmap='Blues',\n",
    "            xticklabels=['Stable','Disruption'],\n",
    "            yticklabels=['Stable','Disruption'], ax=ax)\n",
    "ax.set_xlabel('Predicted'); ax.set_ylabel('Actual')\n",
    "ax.set_title(f'{best_method} (threshold={THRESHOLD:.3f})')\n",
    "plt.tight_layout()\n",
    "plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

# ── Cell 21: SHAP ──────────────────────────────────────────────────────────
cells.append(code([
    "# SHAP Feature Importance\n",
    "gc.collect()\n",
    "SHAP_N = min(3000, len(X_test))\n",
    "X_shap = X_test[:SHAP_N]\n",
    "\n",
    "explainer = shap.TreeExplainer(xgb_bst)\n",
    "shap_vals = explainer.shap_values(xgb.DMatrix(X_shap))\n",
    "\n",
    "plt.figure(figsize=(14, 10))\n",
    "shap.summary_plot(shap_vals, X_shap, feature_names=feature_cols,\n",
    "                  max_display=25, show=False)\n",
    "plt.title('SHAP — Tuned XGBoost (Top 25)')\n",
    "plt.tight_layout()\n",
    "plt.savefig('shap_beeswarm.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "plt.figure(figsize=(14, 10))\n",
    "shap.summary_plot(shap_vals, X_shap, feature_names=feature_cols,\n",
    "                  plot_type='bar', max_display=25, show=False)\n",
    "plt.title('Mean |SHAP| — Tuned XGBoost (Top 25)')\n",
    "plt.tight_layout()\n",
    "plt.savefig('shap_bar.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "del X_shap, shap_vals; gc.collect()"
]))

# ── Cell 22: Optuna Visualization ──────────────────────────────────────────
cells.append(code([
    "# Optuna Trial History\n",
    "fig, axes = plt.subplots(1, 3, figsize=(21, 6))\n",
    "for ax, (name, study) in zip(axes, [('XGBoost', xgb_study),\n",
    "                                     ('LightGBM', lgb_study),\n",
    "                                     ('CatBoost', cat_study)]):\n",
    "    vals = [t.value for t in study.trials if t.value is not None]\n",
    "    ax.plot(range(1,len(vals)+1), vals, 'o-', alpha=0.5, ms=4)\n",
    "    best_so_far = [max(vals[:i+1]) for i in range(len(vals))]\n",
    "    ax.plot(range(1,len(vals)+1), best_so_far, 'r-', lw=2, label='Best')\n",
    "    ax.set_xlabel('Trial'); ax.set_ylabel('AUC')\n",
    "    ax.set_title(f'{name} ({len(vals)} trials)'); ax.legend()\n",
    "plt.tight_layout()\n",
    "plt.savefig('optuna_trials.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

# ── Cell 23: Feature Importance ────────────────────────────────────────────
cells.append(code([
    "# Feature Importance — Top 20\n",
    "fig, axes = plt.subplots(1, 3, figsize=(24, 10))\n",
    "\n",
    "xgb_imp = xgb_bst.get_score(importance_type='gain')\n",
    "xgb_named = {}\n",
    "for k, v in xgb_imp.items():\n",
    "    idx = int(k.replace('f',''))\n",
    "    if idx < len(feature_cols): xgb_named[feature_cols[idx]] = v\n",
    "pd.Series(xgb_named).nlargest(20).plot(kind='barh', ax=axes[0], color='steelblue')\n",
    "axes[0].set_title('XGBoost'); axes[0].set_xlabel('Gain')\n",
    "\n",
    "pd.Series(lgb_model.feature_importances_, index=feature_cols).nlargest(20).plot(\n",
    "    kind='barh', ax=axes[1], color='forestgreen')\n",
    "axes[1].set_title('LightGBM'); axes[1].set_xlabel('Importance')\n",
    "\n",
    "pd.Series(cat_model.feature_importances_, index=feature_cols).nlargest(20).plot(\n",
    "    kind='barh', ax=axes[2], color='darkorange')\n",
    "axes[2].set_title('CatBoost'); axes[2].set_xlabel('Importance')\n",
    "\n",
    "plt.suptitle('Feature Importance — Top 20 per Model', fontsize=14)\n",
    "plt.tight_layout()\n",
    "plt.savefig('feature_importance.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

# ── Cell 24: Export ────────────────────────────────────────────────────────
cells.append(code([
    "# Save everything\n",
    "os.makedirs('improved_outputs', exist_ok=True)\n",
    "\n",
    "xgb_bst.save_model('improved_outputs/xgb_tuned.json')\n",
    "joblib.dump(lgb_model, 'improved_outputs/lgb_tuned.joblib')\n",
    "joblib.dump(cat_model, 'improved_outputs/cat_tuned.joblib')\n",
    "joblib.dump(mlp_model, 'improved_outputs/mlp_model.joblib')\n",
    "joblib.dump(meta_lr,   'improved_outputs/meta_lr_stacking.joblib')\n",
    "joblib.dump(scaler,    'improved_outputs/scaler.joblib')\n",
    "\n",
    "with open('improved_outputs/best_params.json', 'w') as f:\n",
    "    json.dump({\n",
    "        'xgb_params': xgb_study.best_params, 'xgb_cv_auc': xgb_study.best_value,\n",
    "        'lgb_params': lgb_study.best_params, 'lgb_cv_auc': lgb_study.best_value,\n",
    "        'cat_params': cat_study.best_params, 'cat_cv_auc': cat_study.best_value,\n",
    "        'optimal_threshold': float(THRESHOLD),\n",
    "    }, f, indent=2, default=str)\n",
    "\n",
    "rows = []\n",
    "for name, proba in {**models, **results}.items():\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ap  = average_precision_score(y_test, proba)\n",
    "    f1  = f1_score(y_test, (proba >= THRESHOLD).astype(int))\n",
    "    rows.append({'method': name, 'auc': auc, 'ap': ap, 'f1': f1})\n",
    "pd.DataFrame(rows).sort_values('auc', ascending=False).to_csv(\n",
    "    'improved_outputs/results_summary.csv', index=False)\n",
    "\n",
    "with open('improved_outputs/feature_list.txt', 'w') as f:\n",
    "    for feat in feature_cols: f.write(feat + '\\n')\n",
    "\n",
    "for img in glob.glob('*.png'):\n",
    "    shutil.copy(img, f'improved_outputs/{img}')\n",
    "\n",
    "shutil.make_archive('CareAssist_Improved_Outputs', 'zip', 'improved_outputs')\n",
    "print('Created: CareAssist_Improved_Outputs.zip')\n",
    "print(f'\\nFinal best: {best_method} AUC={best_auc:.4f}, threshold={THRESHOLD:.3f}')"
]))

# ── Cell 25: Download ──────────────────────────────────────────────────────
cells.append(code([
    "# Download\n",
    "from google.colab import files\n",
    "files.download('CareAssist_Improved_Outputs.zip')\n",
    "print('Download started!')"
]))

# ═══════════════════════════════════════════════════════════════════════════
notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {"provenance": [], "gpuType": "T4"},
        "kernelspec": {"name": "python3", "display_name": "Python 3"},
        "language_info": {"name": "python"},
        "accelerator": "GPU"
    },
    "cells": cells
}

workspace_dir = os.path.dirname(os.path.abspath(__file__))
output_name = "CareAssist_Improved_Model.ipynb"
path1 = os.path.join(workspace_dir, output_name)
path2 = os.path.join(os.path.expanduser("~"), "Downloads", output_name)

for path in [path1, path2]:
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=1, ensure_ascii=False)
    print(f"Wrote {path} ({os.path.getsize(path):,} bytes)")

with open(path1, 'r', encoding='utf-8') as f:
    nb = json.load(f)
print(f"\nValidation: {len(nb['cells'])} cells, nbformat={nb['nbformat']}")
print("All good!")
