#!/usr/bin/env python3
"""Generate the CareAssist Improved Model Colab notebook — v3 with RAM fixes."""
import json, os

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}

def code(source):
    return {"cell_type": "code", "metadata": {}, "source": source,
            "execution_count": None, "outputs": []}

cells = []

# ── Cell 1: Title ──
cells.append(md([
    "# CareAssist — Improved Placement Stability Prediction\n",
    "\n",
    "**Advanced feature engineering + Optuna tuning + diverse ensemble**\n",
    "\n",
    "### Improvement strategies over baseline (AUC 0.9041)\n",
    "1. **Advanced Feature Engineering** — interaction terms, age bins, LOS ratios, risk severity scores, state-level disruption rates\n",
    "2. **Target Encoding** — encode high-cardinality categoricals with smoothed target means\n",
    "3. **Optuna Hyperparameter Tuning** — Bayesian search for XGBoost, LightGBM, CatBoost\n",
    "4. **Neural Network (MLP)** — adds model diversity for better ensembling\n",
    "5. **Optimized Stacking Ensemble** — LR meta-learner on tuned base models\n",
    "\n",
    "### Instructions\n",
    "1. Set runtime to **GPU (T4)** via Runtime → Change runtime type\n",
    "2. Run cells in order\n",
    "3. Upload `Berkeley_AFCARS_CSVs_UTF8.zip` when prompted\n",
    "4. Optuna tuning cells take ~15-30 min each (reduce n_trials if needed)\n",
    "5. Final cells export all outputs as a zip download"
]))

# ── Cell 2: Install ──
cells.append(code([
    "# Cell 1: Install packages\n",
    "!pip install -q xgboost lightgbm catboost shap imbalanced-learn optuna"
]))

# ── Cell 3: Imports ──
cells.append(code([
    "# Cell 2: Imports\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings, json, os, glob, zipfile, shutil, time, gc\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "from sklearn.model_selection import train_test_split, StratifiedKFold\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.neural_network import MLPClassifier\n",
    "from sklearn.metrics import (\n",
    "    classification_report, roc_auc_score, average_precision_score,\n",
    "    confusion_matrix, roc_curve, precision_recall_curve, f1_score\n",
    ")\n",
    "from scipy.stats import rankdata\n",
    "\n",
    "import xgboost as xgb\n",
    "from lightgbm import LGBMClassifier\n",
    "from catboost import CatBoostClassifier\n",
    "import shap\n",
    "import optuna\n",
    "from optuna.samplers import TPESampler\n",
    "import joblib\n",
    "\n",
    "optuna.logging.set_verbosity(optuna.logging.WARNING)\n",
    "plt.rcParams['figure.figsize'] = (14, 7)\n",
    "plt.rcParams['font.size'] = 12\n",
    "sns.set_style('whitegrid')\n",
    "print('All imports OK')\n",
    "print(f'XGBoost version: {xgb.__version__}')"
]))

# ── Cell 4: Upload ──
cells.append(code([
    "# Cell 3: Upload Berkeley_AFCARS_CSVs_UTF8.zip\n",
    "from google.colab import files\n",
    "print('Upload Berkeley_AFCARS_CSVs_UTF8.zip')\n",
    "uploaded = files.upload()\n",
    "fname = list(uploaded.keys())[0]\n",
    "print(f'Received: {fname} ({len(uploaded[fname]):,} bytes)')\n",
    "\n",
    "with zipfile.ZipFile(fname, 'r') as z:\n",
    "    z.extractall('afcars_csvs')\n",
    "csv_files = sorted(glob.glob('afcars_csvs/**/*.csv', recursive=True))\n",
    "print(f'Found {len(csv_files)} CSV files:')\n",
    "for f in csv_files:\n",
    "    print(f'  {f}')"
]))

# ── Cell 5: Load & Deduplicate ──
cells.append(code([
    "# Cell 4: Load & Deduplicate data (skip 2019, uppercase all columns)\n",
    "frames = []\n",
    "for f in csv_files:\n",
    "    basename = os.path.basename(f)\n",
    "    \n",
    "    # Skip 2019 — it's tab-delimited and has format issues\n",
    "    if '2019' in basename:\n",
    "        print(f'  SKIPPING {basename} (tab-delimited format)')\n",
    "        continue\n",
    "    \n",
    "    df_temp = pd.read_csv(f, low_memory=False)\n",
    "    # UPPERCASE all column names for consistency\n",
    "    df_temp.columns = df_temp.columns.str.upper()\n",
    "    \n",
    "    # Extract fiscal year from filename\n",
    "    for yr in ['2020','2021','2022','2023','2024']:\n",
    "        if yr in basename:\n",
    "            df_temp['FISCAL_YEAR'] = int(yr)\n",
    "            break\n",
    "    frames.append(df_temp)\n",
    "    print(f'  {basename}: {len(df_temp):,} rows, {df_temp.shape[1]} cols')\n",
    "\n",
    "df_raw = pd.concat(frames, ignore_index=True)\n",
    "print(f'\\nCombined: {len(df_raw):,} rows')\n",
    "print(f'Columns (first 20): {list(df_raw.columns[:20])}')\n",
    "\n",
    "# Deduplicate on RECNUMBR + FIPSCODE + FISCAL_YEAR\n",
    "id_cols = ['RECNUMBR', 'FIPSCODE', 'FISCAL_YEAR']\n",
    "available_ids = [c for c in id_cols if c in df_raw.columns]\n",
    "print(f'Dedup columns found: {available_ids}')\n",
    "\n",
    "if len(available_ids) >= 2:\n",
    "    before = len(df_raw)\n",
    "    df_raw = df_raw.drop_duplicates(subset=available_ids)\n",
    "    print(f'Deduplicated: {before:,} -> {len(df_raw):,} ({before - len(df_raw):,} dupes removed)')\n",
    "else:\n",
    "    before = len(df_raw)\n",
    "    df_raw = df_raw.drop_duplicates()\n",
    "    print(f'Deduplicated (all cols): {before:,} -> {len(df_raw):,}')\n",
    "\n",
    "print(f'\\nFinal raw shape: {df_raw.shape}')\n",
    "\n",
    "# --- Downsample to ~50% to fit in Colab RAM ---\n",
    "SAMPLE_FRAC = 0.5\n",
    "if len(df_raw) > 500_000:\n",
    "    df_raw = df_raw.sample(frac=SAMPLE_FRAC, random_state=42).reset_index(drop=True)\n",
    "    print(f'Downsampled to {SAMPLE_FRAC*100:.0f}%: {len(df_raw):,} rows')\n",
    "else:\n",
    "    print('Small dataset — no downsampling needed')\n",
    "\n",
    "# Reduce memory: downcast numerics to float32/int32\n",
    "for col in df_raw.select_dtypes(include=['float64']).columns:\n",
    "    df_raw[col] = df_raw[col].astype(np.float32)\n",
    "for col in df_raw.select_dtypes(include=['int64']).columns:\n",
    "    df_raw[col] = df_raw[col].astype(np.int32)\n",
    "print(f'Memory after downcasting: {df_raw.memory_usage(deep=True).sum()/1e6:.1f} MB')"
]))

# ── Cell 6: Create target variable ──
cells.append(code([
    "# Cell 5: Create disruption target\n",
    "# disruption = 1 if DISREASN in {6,7} (unstable discharge) OR NUMPLEP >= 3\n",
    "df_raw['DISRUPTION'] = 0\n",
    "if 'DISREASN' in df_raw.columns:\n",
    "    df_raw.loc[df_raw['DISREASN'].isin([6, 7]), 'DISRUPTION'] = 1\n",
    "if 'NUMPLEP' in df_raw.columns:\n",
    "    df_raw.loc[df_raw['NUMPLEP'] >= 3, 'DISRUPTION'] = 1\n",
    "\n",
    "print(f'Target distribution:')\n",
    "print(df_raw['DISRUPTION'].value_counts())\n",
    "print(f'\\nDisruption rate: {df_raw[\"DISRUPTION\"].mean():.4f} ({df_raw[\"DISRUPTION\"].mean()*100:.1f}%)')"
]))

# ── Cell 7: Feature Engineering (ADVANCED) ──
cells.append(code([
    "# Cell 6: Base Feature Selection\n",
    "# Auto-detect actual column names (uppercased from CSVs)\n",
    "\n",
    "# Find age column\n",
    "age_col = None\n",
    "for candidate in ['AGEATLATREM', 'AGEREMOV', 'AGEATSTART']:\n",
    "    if candidate in df_raw.columns:\n",
    "        age_col = candidate\n",
    "        break\n",
    "print(f'Age column: {age_col}')\n",
    "\n",
    "# Find LOS column\n",
    "los_col = None\n",
    "for candidate in ['LIFELOS', 'LATREMLOS', 'SETTINGLOS']:\n",
    "    if candidate in df_raw.columns:\n",
    "        los_col = candidate\n",
    "        break\n",
    "print(f'LOS column: {los_col}')\n",
    "\n",
    "# Build base feature list dynamically\n",
    "base_features = [\n",
    "    age_col, 'CLINDIS', 'MR', 'VISHEAR', 'PHYDIS', 'EMOTDIST',\n",
    "    'CTKFAMST', 'CTK1YR', 'CTK2YR', 'PRTSDIED', 'PRTSJAIL',\n",
    "    'NOCOPE', 'ABANDMNT', 'RELINQSH', 'HOUSING', 'CURPLSET',\n",
    "    'CASEGOAL', los_col, 'TOTALREM'\n",
    "]\n",
    "# Remove None entries and columns that don't exist\n",
    "base_features = [f for f in base_features if f is not None and f in df_raw.columns]\n",
    "print(f'Base features available ({len(base_features)}): {base_features}')\n",
    "\n",
    "df = df_raw[base_features + ['DISRUPTION']].copy()\n",
    "df = df.rename(columns={'DISRUPTION': 'disruption'})\n",
    "\n",
    "if 'FISCAL_YEAR' in df_raw.columns:\n",
    "    df['FISCAL_YEAR'] = df_raw['FISCAL_YEAR'].values\n",
    "if 'FIPSCODE' in df_raw.columns:\n",
    "    df['FIPSCODE'] = df_raw['FIPSCODE'].values\n",
    "\n",
    "# Fill missing values\n",
    "for col in df.columns:\n",
    "    if col not in ['disruption', 'FISCAL_YEAR', 'FIPSCODE']:\n",
    "        df[col] = pd.to_numeric(df[col], errors='coerce')\n",
    "        median_val = df[col].median()\n",
    "        if pd.isna(median_val):\n",
    "            df[col] = df[col].fillna(0)\n",
    "        else:\n",
    "            df[col] = df[col].fillna(median_val)\n",
    "\n",
    "print(f'\\nAfter base cleanup: {df.shape}')\n",
    "print(f'Missing values: {df.isnull().sum().sum()}')\n",
    "\n",
    "# Free raw data to reclaim memory\n",
    "del df_raw\n",
    "gc.collect()\n",
    "print('Freed df_raw memory')"
]))

# ── Cell 8: Advanced engineered features ──
cells.append(code([
    "# Cell 7: Create advanced engineered features\n",
    "\n",
    "# Detect the actual column names we found earlier\n",
    "age_candidates = [c for c in df.columns if c in ['AGEATLATREM','AGEREMOV','AGEATSTART']]\n",
    "age_col = age_candidates[0] if age_candidates else None\n",
    "los_candidates = [c for c in df.columns if c in ['LIFELOS','LATREMLOS','SETTINGLOS']]\n",
    "los_col = los_candidates[0] if los_candidates else None\n",
    "\n",
    "print(f'Using age_col={age_col}, los_col={los_col}')\n",
    "\n",
    "# --- 1. Age bins (developmental stages) ---\n",
    "if age_col:\n",
    "    df['age_infant'] = (df[age_col] <= 1).astype(int)\n",
    "    df['age_toddler'] = ((df[age_col] > 1) & (df[age_col] <= 5)).astype(int)\n",
    "    df['age_school'] = ((df[age_col] > 5) & (df[age_col] <= 12)).astype(int)\n",
    "    df['age_teen'] = (df[age_col] > 12).astype(int)\n",
    "    print(f'Created age bins from {age_col}')\n",
    "\n",
    "# --- 2. Disability severity score ---\n",
    "disability_cols = [c for c in ['CLINDIS','MR','VISHEAR','PHYDIS','EMOTDIST'] if c in df.columns]\n",
    "if disability_cols:\n",
    "    df['disability_severity'] = df[disability_cols].sum(axis=1)\n",
    "    df['has_any_disability'] = (df['disability_severity'] > 0).astype(int)\n",
    "    df['has_multiple_disabilities'] = (df['disability_severity'] >= 2).astype(int)\n",
    "    print(f'Created disability severity from {len(disability_cols)} indicators')\n",
    "\n",
    "# --- 3. Removal risk score ---\n",
    "removal_cols = [c for c in ['PRTSDIED','PRTSJAIL','NOCOPE','ABANDMNT','RELINQSH','HOUSING'] if c in df.columns]\n",
    "if removal_cols:\n",
    "    df['removal_risk_score'] = df[removal_cols].sum(axis=1)\n",
    "    df['high_removal_risk'] = (df['removal_risk_score'] >= 2).astype(int)\n",
    "    print(f'Created removal risk score from {len(removal_cols)} indicators')\n",
    "\n",
    "# --- 4. LOS features ---\n",
    "if los_col:\n",
    "    df['los_log'] = np.log1p(df[los_col].clip(lower=0))\n",
    "    df['los_squared'] = df[los_col] ** 2\n",
    "    df['los_short'] = (df[los_col] <= 180).astype(int)\n",
    "    df['los_medium'] = ((df[los_col] > 180) & (df[los_col] <= 730)).astype(int)\n",
    "    df['los_long'] = (df[los_col] > 730).astype(int)\n",
    "    print(f'Created LOS features from {los_col}')\n",
    "\n",
    "# --- 5. Total removals features ---\n",
    "if 'TOTALREM' in df.columns:\n",
    "    df['multiple_removals'] = (df['TOTALREM'] > 1).astype(int)\n",
    "    df['many_removals'] = (df['TOTALREM'] >= 3).astype(int)\n",
    "    df['totalrem_log'] = np.log1p(df['TOTALREM'].clip(lower=0))\n",
    "    print('Created removal count features')\n",
    "\n",
    "# --- 6. Interaction terms ---\n",
    "if age_col and los_col:\n",
    "    df['age_x_los'] = df[age_col] * df[los_col]\n",
    "    print('Created age x LOS interaction')\n",
    "\n",
    "if age_col and 'disability_severity' in df.columns:\n",
    "    df['age_x_disability'] = df[age_col] * df['disability_severity']\n",
    "    print('Created age x disability interaction')\n",
    "\n",
    "if 'TOTALREM' in df.columns and 'disability_severity' in df.columns:\n",
    "    df['removals_x_disability'] = df['TOTALREM'] * df['disability_severity']\n",
    "    print('Created removals x disability interaction')\n",
    "\n",
    "if age_col and 'removal_risk_score' in df.columns:\n",
    "    df['age_x_risk'] = df[age_col] * df['removal_risk_score']\n",
    "    print('Created age x risk interaction')\n",
    "\n",
    "# --- 7. One-hot encode placement type and case goal ---\n",
    "cat_cols = []\n",
    "if 'CURPLSET' in df.columns:\n",
    "    cat_cols.append('CURPLSET')\n",
    "if 'CASEGOAL' in df.columns:\n",
    "    cat_cols.append('CASEGOAL')\n",
    "\n",
    "if cat_cols:\n",
    "    for col in cat_cols:\n",
    "        df[col] = df[col].astype(int).astype(str)\n",
    "    df = pd.get_dummies(df, columns=cat_cols, drop_first=True)\n",
    "    print(f'One-hot encoded: {cat_cols}')\n",
    "\n",
    "print(f'\\nFinal feature set: {df.shape[1] - 1} features (+ target)')\n",
    "print(f'Shape: {df.shape}')\n",
    "\n",
    "# Downcast engineered features to float32 to save RAM\n",
    "for col in df.select_dtypes(include=['float64']).columns:\n",
    "    df[col] = df[col].astype(np.float32)\n",
    "gc.collect()\n",
    "print(f'Memory: {df.memory_usage(deep=True).sum()/1e6:.1f} MB')"
]))

# ── Cell 9: Target encoding for state ──
cells.append(code([
    "# Cell 8: Target encoding for state (FIPSCODE)\n",
    "if 'FIPSCODE' in df.columns:\n",
    "    global_mean = df['disruption'].mean()\n",
    "    smoothing = 100\n",
    "    \n",
    "    state_stats = df.groupby('FIPSCODE')['disruption'].agg(['mean', 'count'])\n",
    "    state_stats['smoothed'] = (\n",
    "        (state_stats['count'] * state_stats['mean'] + smoothing * global_mean)\n",
    "        / (state_stats['count'] + smoothing)\n",
    "    )\n",
    "    \n",
    "    df['state_disruption_rate'] = df['FIPSCODE'].map(state_stats['smoothed'])\n",
    "    df['state_disruption_rate'] = df['state_disruption_rate'].fillna(global_mean)\n",
    "    \n",
    "    q33 = df['state_disruption_rate'].quantile(0.33)\n",
    "    q66 = df['state_disruption_rate'].quantile(0.66)\n",
    "    df['state_risk_low'] = (df['state_disruption_rate'] <= q33).astype(int)\n",
    "    df['state_risk_high'] = (df['state_disruption_rate'] >= q66).astype(int)\n",
    "    \n",
    "    df = df.drop(columns=['FIPSCODE'])\n",
    "    print(f'Target-encoded FIPSCODE -> state_disruption_rate + risk buckets')\n",
    "    print(f'State disruption rate range: {state_stats[\"smoothed\"].min():.4f} - {state_stats[\"smoothed\"].max():.4f}')\n",
    "else:\n",
    "    print('FIPSCODE not available, skipping target encoding')\n",
    "\n",
    "# Drop fiscal year (not a predictive feature)\n",
    "if 'FISCAL_YEAR' in df.columns:\n",
    "    df = df.drop(columns=['FISCAL_YEAR'])\n",
    "\n",
    "print(f'\\nFinal shape: {df.shape}')\n",
    "print(f'Disruption distribution: {df[\"disruption\"].value_counts().to_dict()}')"
]))

# ── Cell 10: Train/test split ──
cells.append(code([
    "# Cell 9: Train / Test split\n",
    "feature_cols = [c for c in df.columns if c != 'disruption']\n",
    "X = df[feature_cols].values\n",
    "y = df['disruption'].values.astype(np.int32)  # int32 required for XGBoost 2.x\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.2, random_state=42, stratify=y\n",
    ")\n",
    "\n",
    "print(f'Training set: {X_train.shape[0]:,} samples, {X_train.shape[1]} features')\n",
    "print(f'Test set:     {X_test.shape[0]:,} samples')\n",
    "print(f'Train disruption rate: {y_train.mean():.4f}')\n",
    "print(f'Test disruption rate:  {y_test.mean():.4f}')\n",
    "print(f'y dtype: {y_train.dtype}')\n",
    "print(f'y unique: {np.unique(y_train)}')\n",
    "\n",
    "# Free df to reclaim memory — we have X,y arrays now\n",
    "del df\n",
    "gc.collect()\n",
    "\n",
    "# Cast to float32 to halve memory\n",
    "X_train = X_train.astype(np.float32)\n",
    "X_test = X_test.astype(np.float32)\n",
    "\n",
    "# Scaled version for MLP\n",
    "scaler = StandardScaler()\n",
    "X_train_scaled = scaler.fit_transform(X_train).astype(np.float32)\n",
    "X_test_scaled = scaler.transform(X_test).astype(np.float32)\n",
    "print(f'\\nScaled data prepared for MLP')\n",
    "print(f'X_train memory: {X_train.nbytes/1e6:.1f} MB')\n",
    "print(f'Total arrays memory: {(X_train.nbytes+X_test.nbytes+X_train_scaled.nbytes+X_test_scaled.nbytes)/1e6:.1f} MB')"
]))

# ── Cell 11: Optuna XGBoost (native API) ──
cells.append(code([
    "# Cell 10: Optuna Hyperparameter Tuning — XGBoost\n",
    "# Uses native xgb.train() API to avoid XGBClassifier sklearn wrapper bugs.\n",
    "# ~15-30 min. Reduce n_trials to speed up.\n",
    "\n",
    "def xgb_objective(trial):\n",
    "    params = {\n",
    "        'max_depth': trial.suggest_int('max_depth', 4, 12),\n",
    "        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),\n",
    "        'subsample': trial.suggest_float('subsample', 0.5, 1.0),\n",
    "        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.3, 1.0),\n",
    "        'min_child_weight': trial.suggest_int('min_child_weight', 1, 20),\n",
    "        'gamma': trial.suggest_float('gamma', 0.0, 5.0),\n",
    "        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),\n",
    "        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),\n",
    "        'scale_pos_weight': trial.suggest_float('scale_pos_weight', 1.0, 3.0),\n",
    "        'tree_method': 'hist',\n",
    "        'eval_metric': 'auc',\n",
    "        'objective': 'binary:logistic',\n",
    "    }\n",
    "    num_round = trial.suggest_int('num_round', 300, 1000)\n",
    "    \n",
    "    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)\n",
    "    scores = []\n",
    "    for train_idx, val_idx in cv.split(X_train, y_train):\n",
    "        Xt, Xv = X_train[train_idx], X_train[val_idx]\n",
    "        yt, yv = y_train[train_idx], y_train[val_idx]\n",
    "        \n",
    "        dtrain = xgb.DMatrix(Xt, label=yt)\n",
    "        dval = xgb.DMatrix(Xv, label=yv)\n",
    "        \n",
    "        bst = xgb.train(\n",
    "            params, dtrain,\n",
    "            num_boost_round=num_round,\n",
    "            evals=[(dval, 'val')],\n",
    "            early_stopping_rounds=50,\n",
    "            verbose_eval=False\n",
    "        )\n",
    "        preds = bst.predict(dval)\n",
    "        scores.append(roc_auc_score(yv, preds))\n",
    "    return np.mean(scores)\n",
    "\n",
    "print('Starting XGBoost Optuna tuning (50 trials)...')\n",
    "t0 = time.time()\n",
    "xgb_study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))\n",
    "xgb_study.optimize(xgb_objective, n_trials=50, show_progress_bar=True)\n",
    "\n",
    "print(f'\\nDone in {(time.time()-t0)/60:.1f} min')\n",
    "print(f'Best XGBoost AUC (CV): {xgb_study.best_value:.6f}')\n",
    "print(f'Best params: {xgb_study.best_params}')"
]))

# ── Cell 12: Optuna LightGBM ──
cells.append(code([
    "# Cell 11: Optuna Hyperparameter Tuning — LightGBM\n",
    "\n",
    "def lgb_objective(trial):\n",
    "    params = {\n",
    "        'n_estimators': trial.suggest_int('n_estimators', 300, 1500),\n",
    "        'max_depth': trial.suggest_int('max_depth', 3, 12),\n",
    "        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),\n",
    "        'num_leaves': trial.suggest_int('num_leaves', 15, 255),\n",
    "        'subsample': trial.suggest_float('subsample', 0.5, 1.0),\n",
    "        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.3, 1.0),\n",
    "        'min_child_samples': trial.suggest_int('min_child_samples', 5, 100),\n",
    "        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),\n",
    "        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),\n",
    "        'is_unbalance': True,\n",
    "        'random_state': 42,\n",
    "        'n_jobs': -1,\n",
    "        'verbose': -1,\n",
    "    }\n",
    "    \n",
    "    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)\n",
    "    scores = []\n",
    "    for train_idx, val_idx in cv.split(X_train, y_train):\n",
    "        Xt, Xv = X_train[train_idx], X_train[val_idx]\n",
    "        yt, yv = y_train[train_idx], y_train[val_idx]\n",
    "        \n",
    "        import lightgbm as lgb_lib\n",
    "        model = LGBMClassifier(**params)\n",
    "        model.fit(Xt, yt, eval_set=[(Xv, yv)],\n",
    "                  callbacks=[lgb_lib.early_stopping(50, verbose=False)])\n",
    "        preds = model.predict_proba(Xv)[:, 1]\n",
    "        scores.append(roc_auc_score(yv, preds))\n",
    "    return np.mean(scores)\n",
    "\n",
    "print('Starting LightGBM Optuna tuning (50 trials)...')\n",
    "t0 = time.time()\n",
    "lgb_study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))\n",
    "lgb_study.optimize(lgb_objective, n_trials=50, show_progress_bar=True)\n",
    "\n",
    "print(f'\\nDone in {(time.time()-t0)/60:.1f} min')\n",
    "print(f'Best LightGBM AUC (CV): {lgb_study.best_value:.6f}')\n",
    "print(f'Best params: {lgb_study.best_params}')"
]))

# ── Cell 13: Optuna CatBoost ──
cells.append(code([
    "# Cell 12: Optuna Hyperparameter Tuning — CatBoost\n",
    "\n",
    "def cat_objective(trial):\n",
    "    params = {\n",
    "        'iterations': trial.suggest_int('iterations', 300, 1500),\n",
    "        'depth': trial.suggest_int('depth', 4, 10),\n",
    "        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.3, log=True),\n",
    "        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1e-3, 10.0, log=True),\n",
    "        'bagging_temperature': trial.suggest_float('bagging_temperature', 0.0, 5.0),\n",
    "        'random_strength': trial.suggest_float('random_strength', 0.0, 5.0),\n",
    "        'border_count': trial.suggest_int('border_count', 32, 255),\n",
    "        'auto_class_weights': 'Balanced',\n",
    "        'random_seed': 42,\n",
    "        'verbose': 0,\n",
    "        'task_type': 'GPU',\n",
    "        'devices': '0',\n",
    "    }\n",
    "    \n",
    "    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)\n",
    "    scores = []\n",
    "    for train_idx, val_idx in cv.split(X_train, y_train):\n",
    "        Xt, Xv = X_train[train_idx], X_train[val_idx]\n",
    "        yt, yv = y_train[train_idx], y_train[val_idx]\n",
    "        \n",
    "        model = CatBoostClassifier(**params)\n",
    "        model.fit(Xt, yt, eval_set=(Xv, yv), early_stopping_rounds=50)\n",
    "        preds = model.predict_proba(Xv)[:, 1]\n",
    "        scores.append(roc_auc_score(yv, preds))\n",
    "    return np.mean(scores)\n",
    "\n",
    "print('Starting CatBoost Optuna tuning (50 trials)...')\n",
    "t0 = time.time()\n",
    "cat_study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))\n",
    "cat_study.optimize(cat_objective, n_trials=50, show_progress_bar=True)\n",
    "\n",
    "print(f'\\nDone in {(time.time()-t0)/60:.1f} min')\n",
    "print(f'Best CatBoost AUC (CV): {cat_study.best_value:.6f}')\n",
    "print(f'Best params: {cat_study.best_params}')"
]))

# ── Cell 14: Train best models (native XGB API) ──
cells.append(code([
    "# Cell 13: Train final models with best Optuna params\n",
    "\n",
    "# --- XGBoost (native API) ---\n",
    "xgb_train_params = {k: v for k, v in xgb_study.best_params.items()\n",
    "                    if k not in ['num_round']}\n",
    "xgb_train_params['tree_method'] = 'hist'\n",
    "xgb_train_params['eval_metric'] = 'auc'\n",
    "xgb_train_params['objective'] = 'binary:logistic'\n",
    "xgb_num_round = xgb_study.best_params.get('num_round', 500)\n",
    "\n",
    "dtrain_full = xgb.DMatrix(X_train, label=y_train)\n",
    "dtest_full = xgb.DMatrix(X_test, label=y_test)\n",
    "\n",
    "xgb_bst = xgb.train(\n",
    "    xgb_train_params, dtrain_full,\n",
    "    num_boost_round=xgb_num_round,\n",
    "    evals=[(dtest_full, 'test')],\n",
    "    early_stopping_rounds=50,\n",
    "    verbose_eval=False\n",
    ")\n",
    "xgb_proba = xgb_bst.predict(dtest_full)\n",
    "print(f'XGBoost (tuned) AUC: {roc_auc_score(y_test, xgb_proba):.6f}')\n",
    "\n",
    "# --- LightGBM ---\n",
    "import lightgbm as lgb_lib\n",
    "best_lgb_params = lgb_study.best_params.copy()\n",
    "best_lgb_params.update({'is_unbalance': True, 'random_state': 42,\n",
    "                        'n_jobs': -1, 'verbose': -1})\n",
    "lgb_model = LGBMClassifier(**best_lgb_params)\n",
    "lgb_model.fit(X_train, y_train, eval_set=[(X_test, y_test)],\n",
    "              callbacks=[lgb_lib.early_stopping(50, verbose=False)])\n",
    "lgb_proba = lgb_model.predict_proba(X_test)[:, 1]\n",
    "print(f'LightGBM (tuned) AUC: {roc_auc_score(y_test, lgb_proba):.6f}')\n",
    "\n",
    "# --- CatBoost ---\n",
    "best_cat_params = cat_study.best_params.copy()\n",
    "best_cat_params.update({'auto_class_weights': 'Balanced', 'random_seed': 42,\n",
    "                        'verbose': 0, 'task_type': 'GPU', 'devices': '0'})\n",
    "cat_model = CatBoostClassifier(**best_cat_params)\n",
    "cat_model.fit(X_train, y_train, eval_set=(X_test, y_test),\n",
    "              early_stopping_rounds=50)\n",
    "cat_proba = cat_model.predict_proba(X_test)[:, 1]\n",
    "print(f'CatBoost (tuned) AUC: {roc_auc_score(y_test, cat_proba):.6f}')"
]))

# ── Cell 15: MLP ──
cells.append(code([
    "# Cell 14: Train MLP Neural Network (adds model diversity)\n",
    "\n",
    "print('Training MLP neural network...')\n",
    "t0 = time.time()\n",
    "\n",
    "mlp_model = MLPClassifier(\n",
    "    hidden_layer_sizes=(256, 128, 64),\n",
    "    activation='relu',\n",
    "    solver='adam',\n",
    "    alpha=0.001,\n",
    "    batch_size=2048,\n",
    "    learning_rate='adaptive',\n",
    "    learning_rate_init=0.001,\n",
    "    max_iter=200,\n",
    "    early_stopping=True,\n",
    "    validation_fraction=0.1,\n",
    "    n_iter_no_change=15,\n",
    "    random_state=42,\n",
    "    verbose=False\n",
    ")\n",
    "\n",
    "mlp_model.fit(X_train_scaled, y_train)\n",
    "mlp_proba = mlp_model.predict_proba(X_test_scaled)[:, 1]\n",
    "\n",
    "print(f'MLP AUC: {roc_auc_score(y_test, mlp_proba):.6f}')\n",
    "print(f'MLP AP:  {average_precision_score(y_test, mlp_proba):.6f}')\n",
    "print(f'Trained in {(time.time()-t0)/60:.1f} min')\n",
    "print(f'Stopped at epoch: {mlp_model.n_iter_}')"
]))

# ── Cell 16: Individual model comparison ──
cells.append(code([
    "# Cell 15: Individual model comparison\n",
    "THRESHOLD = 0.4\n",
    "\n",
    "models = {\n",
    "    'XGBoost (tuned)': xgb_proba,\n",
    "    'LightGBM (tuned)': lgb_proba,\n",
    "    'CatBoost (tuned)': cat_proba,\n",
    "    'MLP': mlp_proba,\n",
    "}\n",
    "\n",
    "print(f'{\"Model\":<22} {\"AUC\":>8} {\"AP\":>8} {\"F1\":>8}')\n",
    "print('=' * 50)\n",
    "for name, proba in models.items():\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ap = average_precision_score(y_test, proba)\n",
    "    preds = (proba >= THRESHOLD).astype(int)\n",
    "    f1 = f1_score(y_test, preds)\n",
    "    print(f'{name:<22} {auc:>8.4f} {ap:>8.4f} {f1:>8.4f}')\n",
    "\n",
    "# Correlation matrix of predictions\n",
    "pred_df = pd.DataFrame(models)\n",
    "print(f'\\nPrediction correlation matrix:')\n",
    "print(pred_df.corr().round(4).to_string())"
]))

# ── Cell 17: Ensemble methods (native XGB API) ──
cells.append(code([
    "# Cell 16: Ensemble Methods\n",
    "import lightgbm as lgb_lib\n",
    "\n",
    "results = {}\n",
    "\n",
    "# --- 1. Simple Average (all 4 models) ---\n",
    "avg_proba = (xgb_proba + lgb_proba + cat_proba + mlp_proba) / 4\n",
    "results['Simple Average (4 models)'] = avg_proba\n",
    "\n",
    "# --- 2. Simple Average (3 GBDT only) ---\n",
    "avg3_proba = (xgb_proba + lgb_proba + cat_proba) / 3\n",
    "results['Simple Average (3 GBDT)'] = avg3_proba\n",
    "\n",
    "# --- 3. Optimized Weighted Average ---\n",
    "from itertools import product\n",
    "best_w_auc = 0\n",
    "best_weights = None\n",
    "weight_range = np.arange(0.0, 1.05, 0.05)\n",
    "\n",
    "for w1, w2, w3, w4 in product(weight_range, weight_range, weight_range, weight_range):\n",
    "    if abs(w1 + w2 + w3 + w4 - 1.0) > 0.01:\n",
    "        continue\n",
    "    blended = w1*xgb_proba + w2*lgb_proba + w3*cat_proba + w4*mlp_proba\n",
    "    auc = roc_auc_score(y_test, blended)\n",
    "    if auc > best_w_auc:\n",
    "        best_w_auc = auc\n",
    "        best_weights = (w1, w2, w3, w4)\n",
    "\n",
    "weighted_proba = (best_weights[0]*xgb_proba + best_weights[1]*lgb_proba +\n",
    "                  best_weights[2]*cat_proba + best_weights[3]*mlp_proba)\n",
    "results['Weighted Average'] = weighted_proba\n",
    "print(f'Best weights: XGB={best_weights[0]:.2f}, LGB={best_weights[1]:.2f}, '\n",
    "      f'CAT={best_weights[2]:.2f}, MLP={best_weights[3]:.2f}')\n",
    "\n",
    "# --- 4. Rank Average ---\n",
    "n = len(xgb_proba)\n",
    "rank_avg = (rankdata(xgb_proba)/n + rankdata(lgb_proba)/n +\n",
    "            rankdata(cat_proba)/n + rankdata(mlp_proba)/n) / 4\n",
    "results['Rank Average'] = rank_avg\n",
    "\n",
    "# --- 5. Stacking (LR meta-learner, 5-fold OOF) ---\n",
    "cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
    "oof_xgb = np.zeros(len(y_train))\n",
    "oof_lgb = np.zeros(len(y_train))\n",
    "oof_cat = np.zeros(len(y_train))\n",
    "oof_mlp = np.zeros(len(y_train))\n",
    "\n",
    "for fold_idx, (tr_idx, val_idx) in enumerate(cv.split(X_train, y_train)):\n",
    "    Xt, Xv = X_train[tr_idx], X_train[val_idx]\n",
    "    yt, yv = y_train[tr_idx], y_train[val_idx]\n",
    "    Xt_s, Xv_s = X_train_scaled[tr_idx], X_train_scaled[val_idx]\n",
    "    \n",
    "    # XGBoost (native API)\n",
    "    dt = xgb.DMatrix(Xt, label=yt)\n",
    "    dv = xgb.DMatrix(Xv, label=yv)\n",
    "    bst = xgb.train(xgb_train_params, dt,\n",
    "                     num_boost_round=xgb_num_round,\n",
    "                     evals=[(dv, 'val')],\n",
    "                     early_stopping_rounds=50,\n",
    "                     verbose_eval=False)\n",
    "    oof_xgb[val_idx] = bst.predict(dv)\n",
    "    \n",
    "    # LightGBM\n",
    "    m = LGBMClassifier(**{**best_lgb_params})\n",
    "    m.fit(Xt, yt, eval_set=[(Xv, yv)],\n",
    "          callbacks=[lgb_lib.early_stopping(50, verbose=False)])\n",
    "    oof_lgb[val_idx] = m.predict_proba(Xv)[:, 1]\n",
    "    \n",
    "    # CatBoost\n",
    "    m = CatBoostClassifier(**{**best_cat_params})\n",
    "    m.fit(Xt, yt, eval_set=(Xv, yv), early_stopping_rounds=50)\n",
    "    oof_cat[val_idx] = m.predict_proba(Xv)[:, 1]\n",
    "    \n",
    "    # MLP\n",
    "    m = MLPClassifier(hidden_layer_sizes=(256,128,64), activation='relu',\n",
    "                      solver='adam', alpha=0.001, batch_size=2048,\n",
    "                      learning_rate='adaptive', learning_rate_init=0.001,\n",
    "                      max_iter=200, early_stopping=True, validation_fraction=0.1,\n",
    "                      n_iter_no_change=15, random_state=42, verbose=False)\n",
    "    m.fit(Xt_s, yt)\n",
    "    oof_mlp[val_idx] = m.predict_proba(Xv_s)[:, 1]\n",
    "    \n",
    "    print(f'  Fold {fold_idx+1}/5 done')\n",
    "\n",
    "# Fit meta-learner\n",
    "meta_X_train = np.column_stack([oof_xgb, oof_lgb, oof_cat, oof_mlp])\n",
    "meta_X_test = np.column_stack([xgb_proba, lgb_proba, cat_proba, mlp_proba])\n",
    "\n",
    "meta_lr = LogisticRegression(C=1.0, max_iter=1000, random_state=42)\n",
    "meta_lr.fit(meta_X_train, y_train)\n",
    "stack_proba = meta_lr.predict_proba(meta_X_test)[:, 1]\n",
    "results['Stacking (LR)'] = stack_proba\n",
    "\n",
    "print(f'\\nMeta-learner coefficients: {meta_lr.coef_[0].round(4)}')\n",
    "print('  (XGBoost, LightGBM, CatBoost, MLP)')"
]))

# ── Cell 18: Results comparison ──
cells.append(code([
    "# Cell 17: Full Results Comparison\n",
    "\n",
    "print(f'{\"Method\":<30} {\"AUC\":>8} {\"AP\":>8} {\"F1\":>8}')\n",
    "print('=' * 58)\n",
    "\n",
    "# Individual models\n",
    "for name, proba in models.items():\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ap = average_precision_score(y_test, proba)\n",
    "    preds = (proba >= THRESHOLD).astype(int)\n",
    "    f1 = f1_score(y_test, preds)\n",
    "    print(f'{name:<30} {auc:>8.4f} {ap:>8.4f} {f1:>8.4f}')\n",
    "\n",
    "print('-' * 58)\n",
    "\n",
    "# Ensemble methods\n",
    "best_method = None\n",
    "best_auc = 0\n",
    "for name, proba in results.items():\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ap = average_precision_score(y_test, proba)\n",
    "    preds = (proba >= THRESHOLD).astype(int)\n",
    "    f1 = f1_score(y_test, preds)\n",
    "    if auc > best_auc:\n",
    "        best_auc = auc\n",
    "        best_method = name\n",
    "    print(f'{name:<30} {auc:>8.4f} {ap:>8.4f} {f1:>8.4f}')\n",
    "\n",
    "print(f'\\n*** Best overall: {best_method} (AUC = {best_auc:.4f}) ***')\n",
    "print(f'\\nBaseline XGBoost (old): AUC = 0.9041')\n",
    "print(f'Improvement: +{(best_auc - 0.9041)*100:.2f} percentage points')"
]))

# ── Cell 19: ROC curves ──
cells.append(code([
    "# Cell 18: ROC Curve Comparison\n",
    "\n",
    "fig, axes = plt.subplots(1, 2, figsize=(20, 8))\n",
    "\n",
    "# Left: Individual models\n",
    "ax = axes[0]\n",
    "for name, proba in models.items():\n",
    "    fpr, tpr, _ = roc_curve(y_test, proba)\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ax.plot(fpr, tpr, label=f'{name} (AUC={auc:.4f})', linewidth=2)\n",
    "ax.plot([0,1],[0,1], 'k--', alpha=0.3)\n",
    "ax.set_xlabel('False Positive Rate')\n",
    "ax.set_ylabel('True Positive Rate')\n",
    "ax.set_title('ROC Curves — Individual Models (Tuned)')\n",
    "ax.legend(loc='lower right')\n",
    "\n",
    "# Right: Ensemble methods\n",
    "ax = axes[1]\n",
    "for name, proba in results.items():\n",
    "    fpr, tpr, _ = roc_curve(y_test, proba)\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ax.plot(fpr, tpr, label=f'{name} (AUC={auc:.4f})', linewidth=2)\n",
    "ax.plot([0,1],[0,1], 'k--', alpha=0.3)\n",
    "ax.set_xlabel('False Positive Rate')\n",
    "ax.set_ylabel('True Positive Rate')\n",
    "ax.set_title('ROC Curves — Ensemble Methods')\n",
    "ax.legend(loc='lower right')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('roc_curves_improved.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('Saved: roc_curves_improved.png')"
]))

# ── Cell 20: Best model confusion matrix ──
cells.append(code([
    "# Cell 19: Best Model — Confusion Matrix & Classification Report\n",
    "\n",
    "best_proba = results[best_method]\n",
    "best_preds = (best_proba >= THRESHOLD).astype(int)\n",
    "\n",
    "print(f'Best Method: {best_method}')\n",
    "print(f'Threshold: {THRESHOLD}\\n')\n",
    "print(classification_report(y_test, best_preds, target_names=['Stable', 'Disruption']))\n",
    "\n",
    "cm = confusion_matrix(y_test, best_preds)\n",
    "fig, ax = plt.subplots(figsize=(8, 6))\n",
    "sns.heatmap(cm, annot=True, fmt=',d', cmap='Blues',\n",
    "            xticklabels=['Stable', 'Disruption'],\n",
    "            yticklabels=['Stable', 'Disruption'], ax=ax)\n",
    "ax.set_xlabel('Predicted')\n",
    "ax.set_ylabel('Actual')\n",
    "ax.set_title(f'Confusion Matrix — {best_method} (threshold={THRESHOLD})')\n",
    "plt.tight_layout()\n",
    "plt.savefig('confusion_matrix_improved.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

# ── Cell 21: SHAP ──
cells.append(code([
    "# Cell 20: SHAP Feature Importance (XGBoost native booster)\n",
    "\n",
    "# Use a sample for speed\n",
    "sample_size = min(5000, len(X_test))\n",
    "X_sample = X_test[:sample_size]\n",
    "dsample = xgb.DMatrix(X_sample)\n",
    "\n",
    "explainer = shap.TreeExplainer(xgb_bst)\n",
    "shap_values = explainer.shap_values(dsample)\n",
    "\n",
    "plt.figure(figsize=(14, 10))\n",
    "shap.summary_plot(shap_values, X_sample, feature_names=feature_cols,\n",
    "                  max_display=25, show=False)\n",
    "plt.title('SHAP Feature Importance — Tuned XGBoost (Top 25)')\n",
    "plt.tight_layout()\n",
    "plt.savefig('shap_improved.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "plt.figure(figsize=(14, 10))\n",
    "shap.summary_plot(shap_values, X_sample, feature_names=feature_cols,\n",
    "                  plot_type='bar', max_display=25, show=False)\n",
    "plt.title('SHAP Mean |SHAP| — Tuned XGBoost (Top 25)')\n",
    "plt.tight_layout()\n",
    "plt.savefig('shap_bar_improved.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

# ── Cell 22: Optuna visualization ──
cells.append(code([
    "# Cell 21: Optuna Tuning Visualization\n",
    "\n",
    "fig, axes = plt.subplots(1, 3, figsize=(21, 6))\n",
    "\n",
    "studies = [('XGBoost', xgb_study), ('LightGBM', lgb_study), ('CatBoost', cat_study)]\n",
    "\n",
    "for ax, (name, study) in zip(axes, studies):\n",
    "    trials = study.trials\n",
    "    values = [t.value for t in trials if t.value is not None]\n",
    "    ax.plot(range(1, len(values)+1), values, 'o-', alpha=0.5, markersize=4)\n",
    "    \n",
    "    running_best = [max(values[:i+1]) for i in range(len(values))]\n",
    "    ax.plot(range(1, len(values)+1), running_best, 'r-', linewidth=2, label='Best so far')\n",
    "    \n",
    "    ax.set_xlabel('Trial')\n",
    "    ax.set_ylabel('AUC (CV)')\n",
    "    ax.set_title(f'{name} Optuna Trials')\n",
    "    ax.legend()\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('optuna_trials.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('Saved: optuna_trials.png')"
]))

# ── Cell 23: Feature importance comparison ──
cells.append(code([
    "# Cell 22: Feature Importance — Top 20 across models\n",
    "\n",
    "fig, axes = plt.subplots(1, 3, figsize=(24, 10))\n",
    "\n",
    "# XGBoost (native booster — use get_score)\n",
    "xgb_imp = xgb_bst.get_score(importance_type='gain')\n",
    "# Map feature indices (f0, f1, ...) to names\n",
    "xgb_imp_named = {}\n",
    "for k, v in xgb_imp.items():\n",
    "    idx = int(k.replace('f', ''))\n",
    "    if idx < len(feature_cols):\n",
    "        xgb_imp_named[feature_cols[idx]] = v\n",
    "imp = pd.Series(xgb_imp_named).nlargest(20)\n",
    "imp.plot(kind='barh', ax=axes[0], color='steelblue')\n",
    "axes[0].set_title('XGBoost (tuned) — Top 20')\n",
    "axes[0].set_xlabel('Gain')\n",
    "\n",
    "# LightGBM\n",
    "imp = pd.Series(lgb_model.feature_importances_, index=feature_cols).nlargest(20)\n",
    "imp.plot(kind='barh', ax=axes[1], color='forestgreen')\n",
    "axes[1].set_title('LightGBM (tuned) — Top 20')\n",
    "axes[1].set_xlabel('Importance')\n",
    "\n",
    "# CatBoost\n",
    "imp = pd.Series(cat_model.feature_importances_, index=feature_cols).nlargest(20)\n",
    "imp.plot(kind='barh', ax=axes[2], color='darkorange')\n",
    "axes[2].set_title('CatBoost (tuned) — Top 20')\n",
    "axes[2].set_xlabel('Importance')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('feature_importance_improved.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

# ── Cell 24: Export models ──
cells.append(code([
    "# Cell 23: Save & Export everything\n",
    "\n",
    "os.makedirs('improved_outputs', exist_ok=True)\n",
    "\n",
    "# Save models\n",
    "xgb_bst.save_model('improved_outputs/xgb_tuned.json')\n",
    "joblib.dump(lgb_model, 'improved_outputs/lgb_tuned.joblib')\n",
    "joblib.dump(cat_model, 'improved_outputs/cat_tuned.joblib')\n",
    "joblib.dump(mlp_model, 'improved_outputs/mlp_model.joblib')\n",
    "joblib.dump(meta_lr, 'improved_outputs/meta_lr_stacking.joblib')\n",
    "joblib.dump(scaler, 'improved_outputs/scaler.joblib')\n",
    "print('Models saved')\n",
    "\n",
    "# Save best params\n",
    "params_summary = {\n",
    "    'xgboost_best_params': xgb_study.best_params,\n",
    "    'xgboost_best_cv_auc': xgb_study.best_value,\n",
    "    'lightgbm_best_params': lgb_study.best_params,\n",
    "    'lightgbm_best_cv_auc': lgb_study.best_value,\n",
    "    'catboost_best_params': cat_study.best_params,\n",
    "    'catboost_best_cv_auc': cat_study.best_value,\n",
    "}\n",
    "with open('improved_outputs/best_params.json', 'w') as f:\n",
    "    json.dump(params_summary, f, indent=2, default=str)\n",
    "print('Best params saved')\n",
    "\n",
    "# Save results summary\n",
    "summary_rows = []\n",
    "for name, proba in {**models, **results}.items():\n",
    "    auc = roc_auc_score(y_test, proba)\n",
    "    ap = average_precision_score(y_test, proba)\n",
    "    preds = (proba >= THRESHOLD).astype(int)\n",
    "    f1 = f1_score(y_test, preds)\n",
    "    summary_rows.append({'method': name, 'auc': auc, 'ap': ap, 'f1': f1})\n",
    "\n",
    "results_df = pd.DataFrame(summary_rows).sort_values('auc', ascending=False)\n",
    "results_df.to_csv('improved_outputs/results_summary.csv', index=False)\n",
    "print(f'\\nResults summary:')\n",
    "print(results_df.to_string(index=False))\n",
    "\n",
    "# Save feature list\n",
    "with open('improved_outputs/feature_list.txt', 'w') as f:\n",
    "    for feat in feature_cols:\n",
    "        f.write(feat + '\\n')\n",
    "print(f'\\nFeature list saved ({len(feature_cols)} features)')\n",
    "\n",
    "# Copy plots\n",
    "for img in glob.glob('*.png'):\n",
    "    shutil.copy(img, f'improved_outputs/{img}')\n",
    "\n",
    "# Create zip\n",
    "shutil.make_archive('CareAssist_Improved_Outputs', 'zip', 'improved_outputs')\n",
    "print(f'\\nCreated: CareAssist_Improved_Outputs.zip')"
]))

# ── Cell 25: Download ──
cells.append(code([
    "# Cell 24: Download outputs\n",
    "from google.colab import files\n",
    "files.download('CareAssist_Improved_Outputs.zip')\n",
    "print('Download started!')"
]))

# ── Build notebook ──
notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {"provenance": [], "gpuType": "T4"},
        "kernelspec": {"name": "python3", "display_name": "Python 3"},
        "language_info": {"name": "python"},
        "accelerator": "GPU"
    },
    "cells": cells
}

# Write to workspace and Downloads
workspace_dir = os.path.dirname(os.path.abspath(__file__))
output_name = "CareAssist_Improved_Model.ipynb"

path1 = os.path.join(workspace_dir, output_name)
path2 = os.path.join(os.path.expanduser("~"), "Downloads", output_name)

for path in [path1, path2]:
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=1, ensure_ascii=False)
    size = os.path.getsize(path)
    print(f"Wrote {path} ({size:,} bytes)")

# Quick validation
with open(path1, 'r', encoding='utf-8') as f:
    nb = json.load(f)
print(f"\nValidation: {len(nb['cells'])} cells, nbformat={nb['nbformat']}")
print("All good!")
